### ISSUE TITLE
Exponentiation derivative

### ISSUE THREAD

**Issue by lcontento** [AMICI-dev/AMICI#1029]
**Problem**
I cannot compute the sensitivities for the following model in the BioModels database (getting `nan` instead)
[https://www.ebi.ac.uk/biomodels/BIOMD0000000529](https://www.ebi.ac.uk/biomodels/BIOMD0000000529)

**To Reproduce**
After downloading the SBML file,
```
import os
import sys
import importlib
import numpy as np
import amici

sbmlImporter = amici.SbmlImporter("BIOMD0000000529.xml")
sbmlImporter.sbml2amici('BIOMD0000000529', 'amici_models')

sys.path.insert(0, os.path.abspath('amici_models'))
model_module = importlib.import_module('BIOMD0000000529')

model = model_module.getModel()
model.setTimepoints(np.linspace(0, 8, 250))
model.requireSensitivitiesForAllParameters()

solver = model.getSolver()
solver.setSensitivityMethod(amici.SensitivityMethod_forward)
solver.setSensitivityOrder(amici.SensitivityOrder_first)

rdata = amici.runAmiciSimulation(model, solver)

# print sensitivity-related results
for key, value in rdata.items():
    if key.startswith('s'):
        print('%12s: ' % key, value)
```

**AMICI version and system environment**
 - OS and version: macOS
 - AMICI interface: Python
 - AMICI version: 0.10.20

**How to fix**
I believe that the problem is due to the way the derivative of exponentiation is computed by SymPy.
For example, the derivative of `t^n` with respect to the parameter `n` is `t^n * log(t)`, but when the base `t` is zero this becomes `nan`.
However, if `n` is non-zero it makes sense to define such derivative as zero.
Since similar expressions appear in the referenced SBML file (see for example the non-constant parameter NS), this results in `nan` being introduced.

If I monkey-patch SymPy's formula for the derivative of exponentiation, then computing the sensitivities appears to work.
```
import sympy as sp
def pow_eval_derivative(self, s):
    dbase = self.base.diff(s)
    dexp = self.exp.diff(s)
    return sp.Piecewise(
        (sp.sympify(0.0), sp.And(sp.Eq(self.base, 0), sp.Eq(dbase, 0))),
        (self * (dexp * sp.log(self.base) + dbase * self.exp/self.base), True)
    )
sp.Pow._eval_derivative = pow_eval_derivative
```

A cleaner way would probably be to define a custom derived class from `sympy.Pow` and then replacing all occurences of `sympy.Pow` inside `sbml2amici`.
However, I am afraid the generated code would be a bit heavy. Maybe it would be better to define a function on the C++ side for computing such derivative?
I am not yet very familiar with `amici`, but I can try to correct this bug and prepare a pull request.

**Comment by FFroehlich** [comment]
Hi @lcontento, thanks for your very detailed error report and proposed fix. We have already implemented a custom power routine on the C++ side, but there currently is no implementation of the derivative. I need to check what the best way to implement this in amici.

**Comment by FFroehlich** [comment]
Okay there is no good way of directly adressing this in C++ and this has to be addressed during symbolic processing. I am fine with directly changing the derivative implementation in sympy, can you submit a PR with the changes you proposed (use `develop` as base branch).
