### ISSUE TITLE
Clean-up steady-state solver code

### ISSUE THREAD

**Issue by paulstapor** [AMICI-dev/AMICI#1073]
Currently, the workSteadyStateProblem routine isn't exactly the nicest part of Amici...
Things to be changed here in some close future:
 - [x] Remove the triple try-catch nesting, when determining whether or not to use simulation 
 - [x] Allow steady-state sensi computation via solving the linear system, if steady-state was computed via simulation: Currently, that's not possible and full FSA computation is carried out, which is fatal for large models.
 - [x] Add flag "simulationOnly" to steadyStateSensitivityMethod, which does not even try to launch the Newton solver.
 - [x] ~#1675~
 - [x] Merge #917 
 - [x] ~Replace custom implementation of iterative linear solver in Newton Solver by~ Interface GMRES, BICGSTAB, and TFQMR (do it analogously to solver.cpp) (#1164 )
 - [ ] correct the (partly) erroneous or misleading output into rdata of the steady state solver
 - [ ] create figure for documenting the steady state solver code via sphinx, rather than having something prerendered
 - [x] #1737

**Comment by dweindl** [comment]
>     * [ ]  Remove the triple try-catch nesting, when determining whether or not to use simulation

Very much in favor. This is a huge pain to debug.

**Comment by FFroehlich** [comment]
> * [ ]  correct the (partly) erroneous or misleading output into rdata of the steady state solver

I have no idea what this refers to, anyone?

**Comment by dweindl** [comment]
Closing this.

Addressed, except for:

>     * [ ]  correct the (partly) erroneous or misleading output into rdata of the steady state solver

Nobody seems to know what that was about. Unlikely to change.

>     * [ ]  create figure for documenting the steady state solver code via sphinx, rather than having something prerendered

Part of https://github.com/AMICI-dev/AMICI/issues/2582
