### ISSUE TITLE
Enable computation of conservation laws in SBML

### ISSUE THREAD

**Issue by paulstapor** [AMICI-dev/AMICI#1074]
Currently, only constant species are allowed. In the long run, we want to support more complex conservation laws here. A reasonable first attempt could be computing the left-kernel of the stoichiometric matrix. This should already cover most of the cases, and can be done cheaply, as not symbolics are involved in finding the conserved quantities at this stage.

**Comment by stephanmg** [comment]
@dweindl does PR #1669 close this issue?

**Comment by dweindl** [comment]
> @dweindl does PR #1669 close this issue?

Partially.

**Comment by dweindl** [comment]
> @dweindl does PR #1669 close this issue?

I think it has been sufficiently addressed for now. Not sure when (or if ever) the unsupported cases will become relevant.
