### ISSUE TITLE
  error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1077]
When running `pip3 install amici`:
<details>
 <summary><pre>error: invalid command 'bdist_wheel'</pre></summary>
<pre>
ERROR: Command errored out with exit status 1:
   command: /home/dweindl/src/PeriNAA-Modeling/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j8fqxrma/amici/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j8fqxrma/amici/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dnbh4wcs
       cwd: /tmp/pip-install-j8fqxrma/amici/
  Complete output (9 lines):
  hdf5.h found in /usr/include/hdf5/serial
  libhdf5.a found in /usr/lib/x86_64-linux-gnu/hdf5/serial
  HDF5 library found. Building AMICI with HDF5 support.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for amici
</pre>
</details>

Installs fine, but is confusing.

I guess this can be fixed somehow in `setup.py`.

**Comment by dilpath** [comment]
When I've seen this error, it was resolved by adding the `wheel` package to the virtual environment with `pip3 install wheel` before running `pip3 install amici` (or other packages).

**Comment by dweindl** [comment]
> When I've seen this error, it was resolved by adding the `wheel` package to the virtual environment with `pip3 install wheel` before running `pip3 install amici` (or other packages).

Yeah, that works, but I was hoping, we could handle that more gracefully in setup.py...

**Comment by dweindl** [comment]
Closed via  #1384
