### ISSUE TITLE
Fix swig typehints for DoubleVector arguments to accept ndarray and others

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1078]
> Unexpected type(s): (Union[ndarray, Tuple[ndarray, Optional[float]]]) Possible types: (DoubleVector)

Not sure how easy to fix, but would be great to avoid false positives in typehint-capable IDEs

**Comment by FFroehlich** [comment]
> > Unexpected type(s): (Union[ndarray, Tuple[ndarray, Optional[float]]]) Possible types: (DoubleVector)
> 
> Not sure how easy to fix, but would be great to avoid false positives in typehint-capable IDEs

Agreed, also not sure how to implement.

**Comment by dweindl** [comment]
Could probably be handled quite well by simple pattern replacement of the wrapper module right after swigging...
