### ISSUE TITLE
Remove `newton_preeq` (Matlab) and `requires_preequilibration` (C++, Python)

### ISSUE THREAD

**Issue by paulstapor** [AMICI-dev/AMICI#1148]
The two flags `newton_preeq` (Matlab) and `requires_preequilibration` (in solver class, C++, Python) don't do anything useful right now and are pure legacy stuff. They keep confusing different users (including me), how they should be set.
At least to what I understand, the question whether preequilibration is done or not is answered based on whether an ExpData object was passed to AMICI whether this object has a nonempty `preequilibrationCondition`.
At least, that's what should decide...

Unless someone else says/knows what these flags would be good for at the moment or any later point, I would suggest to remove them.

**Comment by FFroehlich** [comment]
I think the flag was designed to permit preequilibration even when no expdata was passed, or when the respective preequilibration condition was empty, to indicate that preequilibration should be performed with simulation conditions.

**Comment by paulstapor** [comment]
I think this is what it would do now. However, without passing an edata object, one can not use another condition for preequilibration than for simulation. But if doing so, simulation would a priori not do anything, because the ODE/DAE is in steady state...

**Comment by FFroehlich** [comment]
Unless you are only interested in the steady-state ...

**Comment by dweindl** [comment]
Without having had a closer look at the good, I would agree that it can be removed.

**Comment by paulstapor** [comment]
> Unless you are only interested in the steady-state ...

But then you don't need preequilibration, but would just run postequilibration...

**Comment by FFroehlich** [comment]
> > Unless you are only interested in the steady-state ...
> 
> But then you don't need preequilibration, but would just run postequilibration...

Thats a good point, so I guess its fine to remove.
