### ISSUE TITLE
How to encode splines in the python or C++ interface?

### ISSUE THREAD

**Issue by paulstapor** [AMICI-dev/AMICI#1198]
Matlab had a hand-crafted way of encoding splines in the symbolic interface. However, SBML does not explicitly support splines, for pySB I'm not sure...
I would like to discuss how to best address this issue. Maybe there's an SBML extension. maybe there's some other way... Splines are a useful tool and it would be good if Amici could still support them...

**Comment by paulstapor** [comment]
Just looked into current SBML extensions. There seems to be a planned extension called SBMLmath, but that seems not yet usable. So, I'd be happy about any suggestion here...

Everything that comes to my mind are hacks like "Creating a script, which computes the interpolation polynomial of the spline and modifies the SBML file prior to Amici Import"... That would obviously work, but is not the thing I would really like to go for in Amici...

**Comment by paulstapor** [comment]
As this is currently important in a project of @lcontento , we discussed the following ideas:
Technically, one can encode a spline directly in the SBML by hacking in the formula using polynomials and piecewise in a state assignment rule (good choice would be cubic Hermite splines, due to their simple formulas, but in principle, also classical interpolating splines would work) . However, splines with many nodes will produce monsters of SBML and later then cpp-files, with hours of symbolic processing, which are also inefficient to evaluate numerically.

Another way would be going via some state assignment rule, which contains a specific type of annotation, which AMICI will parse automatically into something which can be turned into C++ code much more elegantly. Roughly, this would be similar to the old Matlab spline implementation. Except, that the old implementation was pretty unsafe C, with some pitfalls due to old, badly documented code, and that it was quite inefficient, as it fully recomputed the interpolation polynomial at each call to the function.

So here's what we came up with:
Let's indeed advice the user to encode a spline in full SBML (if possible and user willing), but at the same time add an annotation. If AMICI finds this annotation, it will discard the state assignemt rule and use its own spline-parser instead. If the spline encoded in SBML is of the same type as requested in the annotation, the AMICI implementation will however produce something which should give exactly the same simulation results as the original SBML file - just more elegant and numerically more efficient.
On the C++-side, I would like to write a spline-class. Each spline used will be an instance of this class, which will replace the species with the state assignment rules and spline annotation. Splines are initialized once before the beginning of the simulation (if it's e.g. an interpolating spline, which isn't our first choice, but would be easy to implement). At this point, the interpolation is carried out once and the spline coefficients are stored as members of the spline object. This will make later calls to splines very efficient.

That's at least our suggestion, which would allow to write valid SBML files which could encode splines that AMICI can parse. If the user additionally encode the original spline formula in the SBML file, every other tool which can simulate SBML models will give the same results as AMICI, just that AMICI will be produce faster and less cumbersome code.

**Comment by dweindl** [comment]
I didn't have any spline application so far. No feeling for how costly which implementation is. Therefore, no strong opinion.

**Comment by FFroehlich** [comment]
> As this is currently important in a project of @lcontento , we discussed the following ideas:
> Technically, one can encode a spline directly in the SBML by hacking in the formula using polynomials and piecewise in a state assignment rule (good choice would be cubic Hermite splines, due to their simple formulas, but in principle, also classical interpolating splines would work) . However, splines with many nodes will produce monsters of SBML and later then cpp-files, with hours of symbolic processing, which are also inefficient to evaluate numerically.
> 
> Another way would be going via some state assignment rule, which contains a specific type of annotation, which AMICI will parse automatically into something which can be turned into C++ code much more elegantly. Roughly, this would be similar to the old Matlab spline implementation. Except, that the old implementation was pretty unsafe C, with some pitfalls due to old, badly documented code, and that it was quite inefficient, as it fully recomputed the interpolation polynomial at each call to the function.
> 
> So here's what we came up with:
> Let's indeed advice the user to encode a spline in full SBML (if possible and user willing), but at the same time add an annotation. If AMICI finds this annotation, it will discard the state assignemt rule and use its own spline-parser instead. If the spline encoded in SBML is of the same type as requested in the annotation, the AMICI implementation will however produce something which should give exactly the same simulation results as the original SBML file - just more elegant and numerically more efficient.
> On the C++-side, I would like to write a spline-class. Each spline used will be an instance of this class, which will replace the species with the state assignment rules and spline annotation. Splines are initialized once before the beginning of the simulation (if it's e.g. an interpolating spline, which isn't our first choice, but would be easy to implement). At this point, the interpolation is carried out once and the spline coefficients are stored as members of the spline object. This will make later calls to splines very efficient.
> 
> That's at least our suggestion, which would allow to write valid SBML files which could encode splines that AMICI can parse. If the user additionally encode the original spline formula in the SBML file, every other tool which can simulate SBML models will give the same results as AMICI, just that AMICI will be produce faster and less cumbersome code.

I generally like the idea of having the implementation of splines in SBML aswell as it makes results more reproducible. I wouldn't go via flag/attribute, but allow the user to specify this as an option when compiling the model. This allows easy testing of the customized solution. 

I like the idea of having spline interpolation evaluate once at setup (maybe also for every reinitialization?) Probably requires some restrictions in terms of allowed arguments (i.e. no state/observable dependencies in spline coefficients) that have to be checked during generation. I have some other application of this in mind, so it may be worthwhile setting this up in a more general fashion that also allows functions other than splines.

**Comment by dweindl** [comment]
> it may be worthwhile setting this up in a more general fashion that also allows functions other than splines.

Agreed. 
I think supporting logicle scaling was also discussed at some occasions...

**Comment by paulstapor** [comment]
> I generally like the idea of having the implementation of splines in SBML aswell as it makes results more reproducible. I wouldn't go via flag/attribute, but allow the user to specify this as an option when compiling the model. This allows easy testing of the customized solution.

Lorenzo wrote a little example code, which adds a specific spline type to the model via a state assignment rule. Added as a tool into either AMICI or somewhere else, this might actually be very helpful...
 
> I like the idea of having spline interpolation evaluate once at setup (maybe also for every reinitialization?) Probably requires some restrictions in terms of allowed arguments (i.e. no state/observable dependencies in spline coefficients) that have to be checked during generation. I have some other application of this in mind, so it may be worthwhile setting this up in a more general fashion that also allows functions other than splines.

Personally, I think spline nodes may depend on parameter, constants, and hard-coded numbers (if e.g. reading in data from a table). Species don't make sense in that context, this would make the full ODE implicit and unsolvable fro CVODES.
However, a faster implementation would be available by forcing every node value to be a parameter...

I'm not sure what's meant with a "more general fashion". What should be more general? The python-sided parser? Or the C++-implementation for simulation? For splines, we had 2 use-cases I know of so far...

**Comment by FFroehlich** [comment]
> I'm not sure what's meant with a "more general fashion". What should be more general? The python-sided parser? Or the C++-implementation for simulation? For splines, we had 2 use-cases I know of so far...

The parent class of the spline class.

**Comment by paulstapor** [comment]
> > I'm not sure what's meant with a "more general fashion". What should be more general? The python-sided parser? Or the C++-implementation for simulation? For splines, we had 2 use-cases I know of so far...
> 
> The parent class of the spline class.

Should be very doable. One could simply make the AbstractSplineClass inherit from a class called "InputFunction" (or even replace it), which is quite similar to AbstracSpline. Then, one could use the spl and sspl arrays (maybe with renaming) for any kind of input function. That should already do most of the job, I think...

**Comment by dweindl** [comment]
> it may be worthwhile setting this up in a more general fashion that also allows functions other than splines

@FFroehlich : Greatly in favor of generalizing that. However, I find it currently a bit hard to imagine what all the different usecases might require. Did you have any specific structure signature in mind? If not, is it okay to go for something spline-specific for a start and generalize that as soon as we have a another concrete application?

**Comment by dweindl** [comment]
https://github.com/AMICI-dev/AMICI/releases/tag/v0.18.0
