### ISSUE TITLE
Upload AMICI SBML Test Suite results to sbml.org

### ISSUE THREAD

**Issue by dilpath** [AMICI-dev/AMICI#1203]
Might help new users
- find AMICI
- assess whether AMICI is appropriate for their model

http://sbml.org/Facilities/Database

**Comment by dweindl** [comment]
Would be nice, agreed. But it seems to be abandoned, see https://github.com/AMICI-dev/AMICI/issues/791. 
We already have the results in the required format (https://github.com/AMICI-dev/AMICI/pull/798)...
