### ISSUE TITLE
Timepoint-specific noise parameters not detected

### ISSUE THREAD

**Issue by yannikschaelte** [AMICI-dev/AMICI#1214]
With @lcontento .

In a PEtab test model (attached), we use a noiseFormula `sqrt(alpha * noiseParameter1_obs1)` with measurement table

```tsv
observableId    simulationConditionId   time    measurement     noiseParameters
obs1    condition1      1.0     3       1.0
obs1    condition1      2.0     -5      0.25
```

Thus, we effectively have a time-dependent sigma. Had we used formula `sqrt(noiseParameter2_obs1 * noiseParameter1_obs1)` with replacement `1.0;alpha` and `0.25;alpha` in the measurement table, this would have been detected. Like this, however AMICI does not see any problem and simulates the model wrongly. Namely, 

```python
from pypesto.petab import PetabImporter
importer = PetabImporter.from_yaml('test.yaml')
objective = importer.create_problem().objective

print(objective(importer.petab_problem.x_nominal_free_scaled))
print(objective([4]))
print(objective([5]))

>>> 204.95158270528947
>>> 204.95158270528947
>>> 204.95158270528947
```

ignores any parameterization and implicitly uses another noise variable (which?).

**Suggestions**
1) Capture such cases and raise a warning (should be possible by evaluating the final noise formula after replacements)
2) Implement timepoint specific noise parameters :) .

**Comment by FFroehlich** [comment]
AMICI itself allows for the specification of timepoint specific sigmas: https://amici.readthedocs.io/en/latest/generated/amici.amici.ExpData.html#amici.amici.ExpData.setObservedDataStdDev

I would assume this function is not used (correctly) in the petab objective?

**Comment by yannikschaelte** [comment]
AMICI allows for timepoint+parameter dependent sigmas?

Ah, the code was not attached. GitHub should have a warning like mails when "attached" is mentioned. Here it comes: [test.zip](https://github.com/AMICI-dev/AMICI/files/5103909/test.zip)

**Comment by FFroehlich** [comment]
> AMICI allows for timepoint+parameter dependent sigmas?
> 
> Ah, the code was not attached. GitHub should have a warning like mails when "attached" is mentioned. Here it comes: [test.zip](https://github.com/AMICI-dev/AMICI/files/5103909/test.zip)

You can specify timepoint dependent sigmas. Additional parameter dependency is not possible.

**Comment by yannikschaelte** [comment]
Yes, the problem is that in this case the parameter dependency was not recognized by PEtab/AMICI. We have set up a check which raises in case timepoint+parameter dependent sigmas are used, which however did not recognize this case here. So in this case the modeler would assume everything is alright, while actually it is not.

**Comment by FFroehlich** [comment]
Makes, sense sorry didn't realise the parameter dependency earlier on. Not straightforward to implement something like that as it probably requires quite a bit of refactoring and a way to specify timepoint-dependencies. 

One (inefficient) approach would be to seperate this into two different simulation conditions where `noiseParameter2_obs1` is encoded as experimental condition. Alternatively one could use heaviside functions to encode temporal dependency, this is likely going to have scaling issues aswell.

Probably worthwhile adding this to the petab testsuite as I would expect that other tools also have issues with dealing such petab problems.

**Comment by yannikschaelte** [comment]
Agreed. I added an issue to the petab test suite for this.

Separating this into different simulation conditions would be not feasible I think, because the real problem has 100 time point units or so, each with their own special parameter. (But there we are currently still investigating alternatives.)

**Comment by FFroehlich** [comment]
@yannikschaelte , this should now correctly be detected in the latest AMICI release, right?

**Comment by yannikschaelte** [comment]
@FFroehlich yes, it is detected by `ValueError: Timepoint-specific parameter overrides currently unsupported.` now!
