### ISSUE TITLE
What's the next thing to be implemented?

### ISSUE THREAD

**Issue by paulstapor** [AMICI-dev/AMICI#1258]
At the moment, some new things are being implemented: Better spline support, some refactoring in the steadystate solver, finite difference features... However, this is going to be done in some not too far future...

As far as I can see, there are two bigger things remaining then:
 * support for events
 * support for second order models

Is it primarily about those two, or am I missing something? What's most pressing or important?
If it's second order support: I think we should discuss what's the best way to implement this... I think there might be a better way than the old implementation, via extending the model (up to discussion)... If someone volunteers for doing this, I could imagine helping...

**Comment by yannikschaelte** [comment]
Those would be the biggest two things from my viewpoint. In addition (but probably easier), observable-dependent sigmas + multiple noise parameters, which could both be addressed by having dJydp, tbd.

**Comment by JanHasenauer** [comment]
I think event support would be more important right now. This is the bottleneck for several benchmark models.

**Comment by dweindl** [comment]
Yes, those would be the biggest ones. In addition to what Yannik mentioned, #1074 and #963 would probably also be good to be addressed.

I would also think that currently events are more relevant for more users than second order sensitivities.

**Comment by paulstapor** [comment]
Thanks already for the opinions. Yes, sure, there are clean-up things to be done before/meanwhile. I'd be happy about addressing more of the [steady state solver milestone](https://github.com/AMICI-dev/AMICI/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Improve+steady+state+solver+code%22) soon.
But both (2nd order and events) will take quite some time of implementation, so it makes sense to do some planning in advance...

**Comment by yannikschaelte** [comment]
In order to use 2nd order optimizers (in particular for the benchmarking study with @LeonardSchmiester ), 2nd order derivatives would be quite interesting too (or we make it a first-order study with potentially the FIM or quasi-Hessian approximations).

**Comment by dweindl** [comment]
I guess this has been answered.
Events are done. 2nd order sensitivities are waiting.
Closing.
