### ISSUE TITLE
AMICI Python documentation recommends a deprecated function as a default example

### ISSUE THREAD

**Issue by zoltuz** [AMICI-dev/AMICI#1260]
**What did you expect to happen?**
A python example that works with future releases 

**What has happened instead?**
Got deprecation warning

**To Reproduce**
*Steps to reproduce the behavior*
http://amici-dev.github.io/AMICI/python_interface.html
*Ideally include minimal code examples here*
```python
observables = amici.assignmentRules2observables(sbml, filter_function=lambda variable:
variable.getId().startswith('observable_') and not variable.getId().endswith('_sigma'))

# in sbml_import.py
   warnings.warn("This function will be removed in future releases.",
                  DeprecationWarning)
```

**AMICI version and system environment**
 - OS and version: [e.g. Ubuntu, iOS, Windows]
 - AMICI interface: [e.g. Python, Matlab, C++]
 - AMICI version:  AMICI v0.11.6
 - Additional information: Compiler name and version used, Python/Matlab version, ...

**How to fix**
Do you know how to resolve the problem?
Change the documentation in way it contains future proof example
Can you submit a pull request?
Yes, but no idea what would be a better example. If you point me to one, I can give a try to update the documentation

**Comment by dweindl** [comment]
Hi Zoltan, you are right. The function will be de-deprecated in the next release. Just ignore the warning for another week or two until that is ready.

**Comment by zoltuz** [comment]
Hi Daniel,
I just wanted to start building a simple example based on the documentation, but it looks like it's not up to date (e.g. it recommends a deprecated function). I started to use the examples from the example folder now, but it would be great if the documentation also shows the latest code to build and run examples.

**Comment by dweindl** [comment]
Hi Zoltan, I am currently working on updating the documentation. As I said, in the next release, this will be fixed (it already is on branch `https://github.com/AMICI-dev/AMICI/tree/develop`).

**Comment by zoltuz** [comment]
That is good news! Thanks for the effort! Let me know if you need a beta
tester for the new python version. I started to play with AMICI in python.

**Comment by dweindl** [comment]
No longer deprecated in v0.11.7. Closing.
