### ISSUE TITLE
Split expressions into static and dynamic

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#1269]
static expressions don't depend on time/states and only need to be evaluated after reinitialization, not at every timepoint.

**Comment by dweindl** [comment]
Also, some expressions only need to be evaluated at measurement timepoints. Could also treat them separately, or just flatten everything in `y` and remove unused expressions afterwards.

**Comment by dweindl** [comment]
If we split the expressions as suggested, how would we handle them in ReturnData? Combine static+dynamic expressions a stick to the current `ReturnData::w`? I.e., the separation of static/dynamic would be hidden to the user.

**Comment by dweindl** [comment]
How to implement?

**A**: `void Model::fw(realtype t, realtype const* x)` -> `void Model::fw(realtype t, realtype const* x, bool static_=true, bool dynamic=true)` 
  body: `if (static_) { /* static exprs */ } if (dynamic) { /* dynamic exprs */ }`

vs 

**B**: add: `void Model::fw_static(realtype t, realtype const* x)`, `void Model::fw_dynamic(realtype t, realtype const* x)`, `void Model::fw(realtype t, realtype const* x) { fw_static(t, x); fw_dynamic(t, x);}`

vs 

**C**: as **B** but with additional split of `w` values into `w_static` + `w_dynamic`


I think I'd go for **A** as this minimizes the required code changes.

**Comment by FFroehlich** [comment]
Yeah _A_ sounds pretty straightforward. Would go for a single flag though as I don't think we ever want to evaluate static only.

**Comment by FFroehlich** [comment]
initial issue was only about `w`. what other expressions could this be applied to?

**Comment by dweindl** [comment]
> initial issue was only about `w`. what other expressions could this be applied to?

Depending on the model, there are quite some time-independent entries for the various derivatives. But not sure whether the benefit outweighs the additional complexity.

**Comment by FFroehlich** [comment]
> > initial issue was only about `w`. what other expressions could this be applied to?
> 
> Depending on the model, there are quite some time-independent entries for the various derivatives. But not sure whether the benefit outweighs the additional complexity.

ah, well , haven't looked at the PR yet, but it would be great to do the same for dwdw, dwdx and dwdp.

**Comment by dweindl** [comment]
Right, but potentially also beyond `dwd*`.

**Comment by dweindl** [comment]
> ah, well , haven't looked at the PR yet, but it would be great to do the same for dwdw, dwdx and dwdp.

I'll look into that separately, after review/merge of #2303.
