### ISSUE TITLE
SegFault in Model compilation after update to v.0.11.7

### ISSUE THREAD

**Issue by jvanhoefer** [AMICI-dev/AMICI#1275]
After updating to version 0.11.7 my python crashes due to a SegFault when compiling a simple model (see the provided files...). This still worked for 0.11.6
[Minimal_Example_Issue.zip](https://github.com/AMICI-dev/AMICI/files/5267115/Minimal_Example_Issue.zip)

**Comment by dweindl** [comment]
Does that still happen with pypesto from https://github.com/ICB-DCM/pyPESTO/pull/469 ?

**Comment by jvanhoefer** [comment]
yes, also happens using the current pypesto develop branch

**Comment by jvanhoefer** [comment]
using the `amici_0117` branch seems to solve it. Thank you.
