### ISSUE TITLE
Problem with libSBML after installing AMICI 0.11.7

### ISSUE THREAD

**Issue by thomassligon** [AMICI-dev/AMICI#1276]
My script uses AMICI, pyPESTO and PETab. With AMICI 0.11.6 it ran far enough to run pyPESTO optimize, but now it crashes without any error message on these statements:
```
import libsbml
converter_config = libsbml.SBMLLocalParameterConverter().getDefaultProperties()
petab_problem.sbml_document.convert(converter_config)
```
I have also observed something odd about libSBML. My package manager (Visual Studio) shows that `python-libsbml 5.18.0` is installed and `5.18.3` is available, but when I try to upgrade it, I get an error:
```
----- Installing 'python-libsbml' -----
ERROR: Could not find a version that satisfies the requirement python-libsbml==5.18.3 (from versions: 5.10.0, 5.10.1, 5.10.2, 5.11.0, 5.11.4, 5.12.1, 5.13.0, 5.15.0, 5.16.0, 5.17.0, 5.18.0)
ERROR: No matching distribution found for python-libsbml==5.18.3
----- Failed to install 'python-libsbml' -----
```
Doing this with `pip install` shows
```
D:\data\Tom\Research\Asthma\python>pip install python-sbml 5.18.3
ERROR: Could not find a version that satisfies the requirement python-sbml (from versions: none)
ERROR: No matching distribution found for python-sbml
```
I haven't found a way to display this information saying that 5.18.3 is available using `pip list`.

**Comment by dweindl** [comment]
Regarding AMICI: 

Not it's a bit harder to figure out what's going wrong without any further information. But the referenced line indicates that it is rather a libsbml issue. So reinstalling that as you tried is my best bet... 

Regarding libsbml: 

> ERROR: Could not find a version that satisfies the requirement python-libsbml==5.18.3 (from versions: 5.10.0, 5.10.1, 5.10.2, 5.11.0, 5.11.4, 5.12.1, 5.13.0, 5.15.0, 5.16.0, 5.17.0, 5.18.0)
> ERROR: No matching distribution found for python-libsbml==5.18.3

Exactly what it says there. There is no 5.18.3 windows distribution (manylinux only, as shown on [pypi](https://pypi.org/project/python-libsbml/5.18.3/#files)). The most recent one for windows is 5.18.0.

**Comment by thomassligon** [comment]
Thanks for the response, it is useful. I have submitted a small "nice to have" report to Visual Studio because the package manager (python environment) is ignoring the OS version when it tells me that a new version is available.
Reinstalling python-libsbml didn't help. I originally asked my question here because the only change I made was to upgrade AMICI from 0.11.16 to 0.11.17, and I thought there might be some known issue.
I don't mind closing this issue, but I think I will leave it open a bit more.
You don't need to look, but if you are interested, the python script is here:
[https://github.com/LeonardSchmiester/AsthmaMapModel/blob/master/python/PE.py](https://github.com/LeonardSchmiester/AsthmaMapModel/blob/master/python/PE.py)

**Comment by dweindl** [comment]
> the only change I made was to upgrade AMICI from 0.11.16 to 0.11.17

It could be the same as #1275 with VS giving wrong clues on where things are going wrong...

**Comment by thomassligon** [comment]
OK, I already saw that issue, but I didn't see a SegFault and it didn't seem to happen to me when compiling a model. Jakob says he fixed the problem by using the amici_0117 branch. I don't see that branch in pyPESTO on GitHub. Am I looking in the wrong place? How can I use a different branch? Do I need to close pyPESTO and install locally, or can I do it directly from GitHub?

**Comment by dweindl** [comment]
Just a guess.. but not sure what else could have happened during that release... It's meanwhile on the `develop` branch there. You need to install pypesto, either from the already cloned repository, or directly from github. Shouldn't matter.

**Comment by thomassligon** [comment]
Good, but I don't know how to do that. I can navigate to [https://github.com/ICB-DCM/pyPESTO/tree/develop](https://github.com/ICB-DCM/pyPESTO/tree/develop), but how do I install it? I can see a `Code` button with the options to clone or download a zip, so I am looking at `pip install -h`. Do I need to run something like
`pip install -e https://github.com/ICB-DCM/pyPESTO/tree/develop`?

**Comment by dweindl** [comment]
>  `pip install -e https://github.com/ICB-DCM/pyPESTO/tree/develop`?

Almost. One option is: `pip3 install https://github.com/ICB-DCM/pyPESTO/archive/develop.zip`

**Comment by thomassligon** [comment]
That fixed the problem. Now I'm back to running optimize, so I should be able to discuss work on the model very soon.
