### ISSUE TITLE
Installing amici package on Windows failed

### ISSUE THREAD

**Issue by feddersmichael** [AMICI-dev/AMICI#1279]
I wanted to install the package by following the instructions from [here](https://github.com/AMICI-dev/AMICI/blob/master/INSTALL.md#windows-using-gcc-mingw) and [here](https://github.com/AMICI-dev/AMICI/issues/425).

Unfortunately I received an error after executing the very last comand 

`pip install --global-option="build_clib" --global-option="--compiler=mingw32" \ --global-option="build_ext" --global-option="--compiler=mingw32" \ amici --no-cache-dir --verbose`

I followed every step given, only exception is that I used the SWIG version 4.0.2 and also changed the PATH variable accordingly.
To not overload the box I copied the error message into a seperate file. Bachelor-Thesis is the name of my anaconda environment. I am very welcome for any help and ofcours willing to clarify my setup if necessary.

[issue.pdf](https://github.com/AMICI-dev/AMICI/files/5334198/issue.pdf)

**Comment by FFroehlich** [comment]
This might be a formatting error for the installation instructions.

Does 

`pip install --global-option="build_clib" --global-option="--compiler=mingw32"  --global-option="build_ext" --global-option="--compiler=mingw32" amici --no-cache-dir --verbose`

work for you?

**Comment by feddersmichael** [comment]
It did run through withoiut an error so thanks for your adjusted code. I still don't see amici as an installed package under my Bachelor-Thesis environment though, so there is still an issue or am I getting something wrong here?
