### ISSUE TITLE
Missing amici.lib on Windows (LNK1181 error)

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1309]
@feddersmichael: Moving to a new issue

> This is the complete output:
[> Amici-Issue.pdf](https://github.com/AMICI-dev/AMICI/files/5397597/Amici-Issue.pdf)
>
> _Originally posted by @feddersmichael in https://github.com/AMICI-dev/AMICI/issue_comments/711172841_

```
LINK : warningLNK4044: Nicht erkannte Option /Wl,-Bstatic; wird ignoriert.\r\n
LINK : warning LNK4044: Nicht erkannte Option /LC:/OpenBLAS-v0.2.19-Win64-int32/lib; wird ignoriert.\r\n
LINK : warning LNK4044: Nicht erkannte Option /lopenblas; wird ignoriert.\r\n
LINK : warning LNK4044: Nicht erkannte Option /Wl,-Bdynamic; wird ignoriert.\r\n
LINK : fatal error LNK1181: Eingabedatei "amici.lib" kann nicht ge\x94ffnet werden.#
```

The latter one shows that AMICI hasn't been installed correctly. Did you ever run any model simulation successfully?

How did you install AMICI?

**Comment by feddersmichael** [comment]
I installed AMICI with Anaconda on Windows, actually I tried these examples out to see whether the installation worked out successfully. I also used [this](https://github.com/AMICI-dev/AMICI/issues/1279) advice.

**Comment by dweindl** [comment]
Okay, can you please reinstall amici with `--verbose` and post the full output?

**Comment by feddersmichael** [comment]
Okay.
[AMICI-installation-issue.pdf](https://github.com/AMICI-dev/AMICI/files/5397803/AMICI-installation-issue.pdf)

**Comment by dweindl** [comment]
Okay, installation seems to fine. The problem is that you used the mingw compiler for AMICI installation but msvc for building the model. That will not work. Assuming that that was not intended, but rather due to lack of documentation, you can add the following lines at the beginning of your code and retry model import:
```
import os
os.environ['CC'] = 'mingw32'
os.environ['CXX'] = 'mingw32'
```
(or set those environment variables elsewhere).

Note that also `BLAS_CFLAGS` and `BLAS_LIBS` need to be set during model import, not only during AMICI installation.

**Comment by feddersmichael** [comment]
I am not completely sure whether I understood you correctly. For example at [this simulation](https://github.com/ICB-DCM/pyPESTO/blob/master/doc/example/sampling_diagnostics.ipynb) should I add the two lines into the first code cell after `import os`? Also do you mean with setting `BLAS_CFLAGS` and `CLAS_LIBS` that I should leave the environment variables in the PATH? I did both things accordingly and the error was still the same.

**Comment by dweindl** [comment]
> I am not completely sure whether I understood you correctly. For example at [this simulation](https://github.com/ICB-DCM/pyPESTO/blob/master/doc/example/sampling_diagnostics.ipynb) should I add the two lines into the first code cell after `import os`? 

I don't see `import os` there, but it needs to be set (anywhere) before `importer = pypesto.petab.PetabImporter(petab_problem)`.

> Also do you mean with setting `BLAS_CFLAGS` and `CLAS_LIBS` that I should leave the environment variables in the PATH? 

Exactly.

> I did both things accordingly and the error was still the same.

You set `CC`/`CXX` before the `PetabImporter` line?

**Comment by feddersmichael** [comment]
Sorry for not responding, the first two I did accordingly, but I don't really know what you mean by setting `CC`/`CXX`. So I probably did not set them.

**Comment by dweindl** [comment]
>I don't really know what you mean by setting `CC`/`CXX`. So I probably did not set them.

By the latter I meant this snippet:
```
import os
os.environ['CC'] = 'mingw32'
os.environ['CXX'] = 'mingw32'
```
or settings the `CC`/`CXX` environment variables in some other way.

So at the time of calling `importer = pypesto.petab.PetabImporter(petab_problem)`, those environment variables have been set to mingw32 and you still get the same compilation errors as before?

**Comment by feddersmichael** [comment]
Yes exactly, I tried it for example with [this document](http://localhost:8889/notebooks/doc/example/sampling_diagnostics.ipynb) and added tthe two lines and still got the same error.
These are the two variables which I set.
![System variable 1](https://user-images.githubusercontent.com/56444515/97636667-beb62c00-1a39-11eb-96b4-333697281976.JPG)
![system variable 2](https://user-images.githubusercontent.com/56444515/97636674-c1188600-1a39-11eb-9103-19cc3d63af86.JPG)

**Comment by dweindl** [comment]
Your screenshots show values of `BLAS_CFLAGS` and `BLAS_LIBS`, but not of `CC` and `CXX`. Just to be sure: you did also set the latter two?

**Comment by feddersmichael** [comment]
Until now I only added the lines in the code cell, do I understand it correct that the name should be `CC` and `CXX` and the value `mingw32` respectively for the system variables? Then I will try that as well, sorry for the confusion.

**Comment by dweindl** [comment]
> Until now I only added the lines in the code cell, do I understand it correct that the name should be `CC` and `CXX` and the value `mingw32` respectively for the system variables?

The environment variables  `CC` and `CXX` need to be set before calling `pypesto.petab.PetabImporter(petab_problem)`. Whether you do that via the Windows dialog (your screenshots) or via Python (the `os.environ` lines doesn't matter). Just make sure they are set to the right value. In particular when set outside your Python session, make sure they are available there (e.g. `print(os.environ['CC'])`).

If you are sure that all is set correctly, and still get the old error, let's take some complexity out and test things without pypesto.
Try running the [sbml import example](https://github.com/AMICI-dev/AMICI/blob/develop/python/examples/example_steadystate/ExampleSteadystate.ipynb) (don't forget to download the model file included in that directory). If you run the notebook as is, you will probably run into the same error as before. Does it change if you include `compiler='mingw32'` as additional argument to `sbml_importer.sbml2amici`?

**Comment by feddersmichael** [comment]
First of all I include the two environment variables and still got the same error.
![environment variable 1](https://user-images.githubusercontent.com/56444515/97875004-1abed000-1d1a-11eb-9e4d-459a83f4521f.JPG)
![environment variable 2](https://user-images.githubusercontent.com/56444515/97875009-1b576680-1d1a-11eb-9ca6-41be3bb0decd.JPG)
Afterwards I tried out the sbml import example and got a similar error, but not quite the same
[Unbenannt 1.pdf](https://github.com/AMICI-dev/AMICI/files/5475415/Unbenannt.1.pdf)
Finally I added the extra argument and got no error while executing the code cell with the `sbml_importer.sbml2amici`.

**Comment by dweindl** [comment]
>  Finally I added the extra argument and got no error while executing the code cell with the `sbml_importer.sbml2amici`.

Okay, great. Seems like `CC`/ `CXX` aren't taken into account here by distutils. 

- [ ] Will submit a PR later this week or next week to change that inside AMICI. 
- [ ] At the same time, it would be good to allow passing through that `compiler` argument from pypesto.

**Comment by dweindl** [comment]
> Seems like `CC`/ `CXX` aren't taken into account here by distutils.

Seems to be a Windows issue

>     * [ ]  At the same time, it would be good to allow passing through that `compiler` argument from pypesto.

Actually, this is already possible. 

@feddersmichael :  Does `problem = importer.create_problem(compiler='mingw32')` work for your original problem?

>     * [ ]  Will submit a PR later this week or next week to change that inside AMICI.

Maybe not. This should be handled properly by distutils. Maybe not helpful to add more complexity to AMICI for that...

**Comment by feddersmichael** [comment]
I tried it out with `problem = importer.create_problem(compiler='mingw32')` and there was still an error although it took significantly longer until it arised.
[error-log.pdf](https://github.com/AMICI-dev/AMICI/files/5509698/error-log.pdf)

**Comment by dweindl** [comment]
Ah, I see. The arguments are passed to the wrong function. Surprised that this doesn't error.

Then you will have to go a slightly more complicated way:

Instead of `problem = importer.create_problem(compiler='mingw32')`, do:

```
model = importer.create_model(compiler='mingw32')
objective = importer.create_objective(model=model)
problem = importer.create_problem(objective=objective)
```
