### ISSUE TITLE
Initial concentrations not overwritten after preequilibration

### ISSUE THREAD

**Issue by LeonardSchmiester** [AMICI-dev/AMICI#1319]
**What did you expect to happen?**
I have a model, where I want to reset initial concentrations for some species (in my case different drugs) after preequilibration. In the SBML file, I have an initial assignment to the species, which is set to 0 for the preeq condition in the PEtab condition file and then to e.g. 10 for the simulation condition. I would have expected `x0` in `rdata` for this species to be 10.

**What has happened instead?**
It seems like the initial concentration of the species is not overwritten with the value in the condition file. So in the above example `x0` is 0. If I delete the preeq condition, `x0` is set correctly.

**To Reproduce**
Here is a minimal example to reproduce the problem: [minimal_example.tar.gz](https://github.com/AMICI-dev/AMICI/files/5428256/minimal_example.tar.gz)

**AMICI version and system environment**
 - OS and version: Ubuntu
 - AMICI interface: Python
 - AMICI version: 0.11.8

**Comment by paulstapor** [comment]
Might be that this has something to do with `model.setReinitializeFixedParameterInitialStates()`? If this flag isn't set to `True`, model simulation will show exactly the behavior you described...

**Comment by LeonardSchmiester** [comment]
Thanks for the hint @paulstapor . This indeed fixed the problem for the minimal example. Will also try for the large model now.

**Comment by dweindl** [comment]
Okay, the problem here is that `simulate_petab` does not handle that correctly for `initialAssignment`s, but only if you have a species name in the condition table.

**Comment by dweindl** [comment]
I am not completely sure how that should be handled (-> https://github.com/PEtab-dev/PEtab/issues/481).

**Comment by LeonardSchmiester** [comment]
> Okay, the problem here is that `simulate_petab` does not handle that correctly for `initialAssignment`s, but only if you have a species name in the condition table.

Using the species Id indeed gives the results I expected.

**Comment by dweindl** [comment]
As this turns out to be slightly more complicated (https://github.com/PEtab-dev/PEtab/issues/481), I'd suggest to only add support for simple initial assignments for now, i.e. those with math elements consisting of a single parameter that is not a target of other rules. The rest should trigger a `NotImplementedError`. Will fix this problem here. Anything beyond can be addressed elsewhere.

**Comment by dweindl** [comment]
Should be fixed in 0.11.13
