### ISSUE TITLE
ReturnData::sllh not set to NaN upon backwards integration failures 

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1325]
Upon backwards integration failures, `ReturnData::sllh` should be set to NaN instead of being left in an undefined state. This seems to be broken.

Invalidating sllh seems to rely on `BackwardProblem*` being `nullptr` in `ReturnData::processSimulationObjects`. Not sure in which situations that would be the case, but not when running into `IntegrationFailureB`.

**Comment by dweindl** [comment]
P.S.: Probably there is a similar issue with forward integration errors and not invalidating `ReturnData::llh` at https://github.com/AMICI-dev/AMICI/blob/787759d2edeaad1804446a5dffea8fce006060a8/src/rdata.cpp#L159-L162

**Comment by dweindl** [comment]
> Invalidating sllh seems to rely on `BackwardProblem*` being `nullptr` in `ReturnData::processSimulationObjects`. Not sure in which situations that would be the case, but not when running into `IntegrationFailureB`.

Fixable by `bwd = nullptr;` when catching `IntegrationFailureB`. Doesn't look too beautiful, though. What do you think @FFroehlich?

**Comment by FFroehlich** [comment]
> > Invalidating sllh seems to rely on `BackwardProblem*` being `nullptr` in `ReturnData::processSimulationObjects`. Not sure in which situations that would be the case, but not when running into `IntegrationFailureB`.
> 
> Fixable by `bwd = nullptr;` when catching `IntegrationFailureB`. Doesn't look too beautiful, though. What do you think @FFroehlich?

You are referring to 
https://github.com/AMICI-dev/AMICI/blob/6aa87c34ab80c5a5e6be40b4bcccf3386e316047/src/amici.cpp#L166
and
https://github.com/AMICI-dev/AMICI/blob/6aa87c34ab80c5a5e6be40b4bcccf3386e316047/src/amici.cpp#L174
correct?

From what I can tell, forward integration failures are accounted for in 
https://github.com/AMICI-dev/AMICI/blob/6aa87c34ab80c5a5e6be40b4bcccf3386e316047/src/rdata.cpp#L263
but a similar check is missing for backwards integration. Something like checking that bwd.t_ == min(model_->t0(), edata_->t_presim) ? Or introducing a flag that is set at the end of `BackwardProblem::workBackwardProblem()` which indicates no error occured?

**Comment by dweindl** [comment]
> You are referring to [...]

Correct. 

> Something like checking that bwd.t_ == min(model_->t0(), edata_->t_presim) 

Should work. Unless there is a problem at exactly `t0()`.

>  introducing a flag that is set at the end of BackwardProblem::workBackwardProblem()

Would allow to account for any other potentially error-causing post-processing. I think I'd prefer this way.

**Comment by FFroehlich** [comment]
> > You are referring to [...]
> 
> Correct.
> 
> > Something like checking that bwd.t_ == min(model_->t0(), edata_->t_presim)
> 
> Should work. Unless there is a problem at exactly `t0()`.
> 
> > introducing a flag that is set at the end of BackwardProblem::workBackwardProblem()
> 
> Would allow to account for any other potentially error-causing post-processing. I think I'd prefer this way.

Agreed, more robust.

**Comment by dweindl** [comment]
On second thought: `BackwardProblem` is doing it's job well by throwing an integration error. I don't think we need any status tracking beyond that. The respective flag should rather go into `runAmiciSimulation`, which is messing things up by just ignoring the exception.

**Comment by FFroehlich** [comment]
> On second thought: `BackwardProblem` is doing it's job well by throwing an integration error. I don't think we need any status tracking beyond that. The respective flag should rather go into `runAmiciSimulation`, which is messing things up by just ignoring the exception.

In the current implementation that would indeed work, but if we end up extending runAmiciSimulation for things like sequences of experiments this would change and I think its simpler if all the problems independently keep track whether they successfully finished or not. Accordingly, I would prefer the flag in BackwardProblem.

**Comment by dweindl** [comment]
> In the current implementation that would indeed work, but if we end up extending runAmiciSimulation for things like sequences of experiments this would change and I think its simpler if all the problems independently keep track whether they successfully finished or not. Accordingly, I would prefer the flag in BackwardProblem.

If we do that, then, in my opinion, `BackwardProblem::workBackwardProblem` shouldn't throw anything anymore, but only report via some status flag.

**Comment by dweindl** [comment]
To be more precise, 
https://github.com/AMICI-dev/AMICI/blob/6aa87c34ab80c5a5e6be40b4bcccf3386e316047/src/amici.cpp#L119
and 
https://github.com/AMICI-dev/AMICI/blob/6aa87c34ab80c5a5e6be40b4bcccf3386e316047/src/amici.cpp#L166-L192
should disappear then.

**Comment by FFroehlich** [comment]
> To be more precise,
> 
> https://github.com/AMICI-dev/AMICI/blob/6aa87c34ab80c5a5e6be40b4bcccf3386e316047/src/amici.cpp#L119
> 
> 
> and
> https://github.com/AMICI-dev/AMICI/blob/6aa87c34ab80c5a5e6be40b4bcccf3386e316047/src/amici.cpp#L166-L192
> 
> 
> should disappear then.

Yes.

**Comment by FFroehlich** [comment]
We still do want those warnings though. Maybe easier to set the flag in those try/catch statements for now and worry about the refactoring as soon as we know what the requirements look like.
