### ISSUE TITLE
Bug when importing simple piecewise model on develop

### ISSUE THREAD

**Issue by paulstapor** [AMICI-dev/AMICI#1328]
I tried to import a model using a very simple piecewise function.

**What did you expect to happen?**
Model import in finite time.

**What has happened instead?**
Computing the derivative `dwdw`(think it was this one) got trapped in an infinite loop.
At least, this is what it looks like.
Problem only exists on current develop, not on master. Therefore, we should not make a new release until this issue here has been fixed... No clue, how this was not detected by CI...

**To Reproduce**
I attached the sbml file to reproduce. Here's my code to run the import:
```
import amici


# SBML model we want to import
sbml_file = 'step_function.xml'
model_name = 'simple_heaviside'
model_output_dir = model_name

# Create an SbmlImporter instance for our SBML model
sbml_importer = amici.SbmlImporter(sbml_file)

import logging
sbml_importer.sbml2amici(model_name,
                         model_output_dir,
                         verbose=logging.DEBUG)
```

**AMICI version and system environment**
 - OS and version: Ubuntu 20.04
 - AMICI interface: Python
 - AMICI version: current develop, 0.11.8 (problem not present on master)
 - Additional information: python 3.8.5

**How to fix**
Have to look into the code of current develop. No clue, what's going wrong exactly...

[step_function.zip](https://github.com/AMICI-dev/AMICI/files/5460135/step_function.zip)

**Comment by paulstapor** [comment]
Seems like #1315 was the culprit. Will have a closer look next week.

**Comment by FFroehlich** [comment]
Creating a assignment rule that assigns SBML `time` to the parameter `t` is both unnecessary and not handled correctly in AMICI, will fix.

**Comment by FFroehlich** [comment]
Fixed on develop
