### ISSUE TITLE
Update publications

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#1330]
2020:

Add: Receptor-Driven ERK Pulses Reconfigure MAPK Signaling and Enable Persistence of Drug-Adapted BRAF-Mutant Melanoma Cells (https://www.sciencedirect.com/science/article/pii/S2405471220303707)

Add: A quantitative analysis of cell-specific contributions and the role of anesthetics to the neurovascular coupling (https://www.sciencedirect.com/science/article/pii/S1053811920303141, unfortunately not referenced in main manuscript, only supplement ...)

Add: Thesis https://www.diva-portal.org/smash/get/diva2:1456998/FULLTEXT03.pdf (includes unpublished manuscript)

Add: A dual-parameter identification approach for data-based predictive modeling of hybrid gene regulatory network-growth kinetics in Pseudomonas putida mt-2 (https://link.springer.com/article/10.1007%2Fs00449-020-02360-2)

Add: PDE-constrained optimization for estimating population dynamics over cell cycle from static single cell measurements (https://www.biorxiv.org/content/10.1101/2020.03.30.015909v1.abstract)

Add: COVID-19 outbreak in Wuhan demonstrates the limitations of publicly available case numbers for epidemiological modelling. (https://www.medrxiv.org/content/10.1101/2020.04.19.20071597v1)

Add: Combination Treatment Optimization Using a Pan-Cancer Pathway Model (https://www.biorxiv.org/content/10.1101/2020.07.05.184960v1.abstract)

Add: Computational modeling reveals cell-cycle dependent kinetics of H4K20 methylation states during Xenopus embryogenesis (https://www.biorxiv.org/content/10.1101/2020.05.28.110684v1.full.pdf)

Add: Efficient Exact Inference for Dynamical Systems with Noisy Measurements using Sequential Approximate Bayesian Computation (https://www.biorxiv.org/content/10.1101/2020.01.30.927004v1)

2019:

Add: Cell-to-cell variability in JAK2/STAT5 pathway components and cytoplasmic volumes define survival threshold in erythroid progenitor cells (https://www.biorxiv.org/content/10.1101/866871v2.abstract)

Add: Identifiability of parameters in PBPK models (https://odr.chalmers.se/bitstream/20.500.12380/256855/1/256855.pdf)

2018:

Add: Critical Assessment of Parameter Estimation Methods in Models of Biological Oscillators (https://www.sciencedirect.com/science/article/pii/S2405896318316999)

**Comment by FFroehlich** [comment]
2016:

Add: Quantitative comparison of competing PDE models for Pomlp dynamics in fission yeast (https://www.sciencedirect.com/science/article/pii/S2405896316327999)

**Comment by dweindl** [comment]
Thanks, added in #1331.

**Comment by FFroehlich** [comment]
Add: A Simple and Efficient Pipeline for Construction, Merging, Expansion, and Simulation of Large-Scale, Single-Cell Mechanistic Models (https://www.biorxiv.org/content/10.1101/2020.11.09.373407v1.full.pdf)
