### ISSUE TITLE
Double check FIM approximation with parameter dependent sigma

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#1335]
Numerical optimization experiments suggest that we may not be doing the right there.

**Comment by paulstapor** [comment]
I know. I implemented another approximation a long time ago, but had no good model and optimizer to test that.
Happy to provide a better approximation

**Comment by FFroehlich** [comment]
I think it was `Schwen_PONE2014` with which I was struggling for a long time until I figured out that this was the problem (BFGS made all the convergence issues go away).

**Comment by paulstapor** [comment]
ok, thanks! The old branch with the "better" FIM should still be around somewhere. Will give it a try

**Comment by FFroehlich** [comment]
Just realised that `Zheng_PNAS2012` also has parameter dependent sigma, but didn't encounter any problems there.

**Comment by paulstapor** [comment]
May be... but Zheng has only one sigma parameter for all datapoints... That amounts probably more or less t something like ordinary least squares...

**Comment by paulstapor** [comment]
What optimizer do you suggest to double check this? Or do you want to do that?

**Comment by FFroehlich** [comment]
> What optimizer do you suggest to double check this? Or do you want to do that?

Fides, I can give it a try over the weekend.

**Comment by paulstapor** [comment]
Just also trying it over night... Let's see, what comes out.
