### ISSUE TITLE
IndexError in amici/logging.py:wrapper_timer

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1347]
When using AMICI from within snakemake, I run into the following error:

```
IndexError: list index out of range

  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/amici/logging.py", line 186, in wrapper_timer
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/inspect.py", line 1491, in getouterframes
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/inspect.py", line 1465, in getframeinfo
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/inspect.py", line 840, in findsource
```

Not yet sure where the underlying problem comes from, but it effectively prevents using AMICI functions decorated with `log_execution_time` from within a snakemake workflow.

**Comment by FFroehlich** [comment]
I have been using amici withing snakemake for multiple years now. How are you calling amici?

**Comment by FFroehlich** [comment]
Probably happens when calling amici directly from snakemake. According to `https://docs.python.org/3/library/inspect.html`, return of `inspect.currentframe()` may differ across interpreters, so snakemake might be doing something funky there. Should probably sanity check the return before handing it off to `inspect.getouterframes()`.

**Comment by dweindl** [comment]
> How are you calling amici?

currently something in `run:` calls something that calls ... that calls amici. Trying to get to a minimal example, but not too successful yet.

**Comment by dweindl** [comment]
PS: yes, putting the `run:` block in a separate script would probably do the job. But I don't want that here :).

**Comment by dweindl** [comment]
Having a hard time getting to the source of the issue. The code context and the line numbers in `inspect.findsource` don't match up. #1348 fixes it, without impairing any other functionality.
