### ISSUE TITLE
support max-functions in observable definition

### ISSUE THREAD

**Issue by jvanhoefer** [AMICI-dev/AMICI#1353]
A model of mine/Caro has `max` functions in the observable definitions. This is currently not supported. (Can send you the model + error messages, if this helps :) )

**Comment by FFroehlich** [comment]
Can you check whether this now works with `0.11.11`?

**Comment by jvanhoefer** [comment]
Sorry, I forgot to give feedback here due to Christmas. Yes, the issue seems to be solved now :) Thank you for implementing this :)
