### ISSUE TITLE
requirements sympy >= 1.7

### ISSUE THREAD

**Issue by jvanhoefer** [AMICI-dev/AMICI#1355]
just a minor thing, but the newest AMICI version seems to need simply version 1.7, with 1.6.1 I got an `ImportError` for `import amici` in 

https://github.com/AMICI-dev/AMICI/blob/275e599ecb87c6f76fa576f5990fae1d8cc8a810/python/amici/ode_export.py#L34

However, `sympy >= 1.7` seems to be not in the requirements (at least pip didn't automatically upgrade, when installing the newest AMICI...)

**Comment by lcontento** [comment]
In SymPy 1.6 `cxxcode` is in `sympy.printing.cxxcode`. But it should be sufficient to import it from `sympy.printing` which should work with both versions. Will make a small PR.
