### ISSUE TITLE
Include expression IDs in generated models

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1373]
So far, observable/parameter/state IDs/names are available in AMICI models. Expressions IDs/names are not. Would be convenient to have them available too (e.g. for debugging, and they would be handy for more informative error messages). Does anything speak against adding those?

**Comment by paulstapor** [comment]
Not at all, would be happy to have them, to be honest.

**Comment by FFroehlich** [comment]
Agreed
