### ISSUE TITLE
Reshaping rdata fields working incorrectly after integration failure

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#1401]
probably affects all diagnosis variables such as `numteps`. Only values up to integration failure are available, so full vector may be shorter than full timevector.

**Comment by dweindl** [comment]
How do we want to address that? Infer the number of timepoints from the actual size, or ensure those variables always have the expected size?

**Comment by FFroehlich** [comment]
> How do we want to address that? Infer the number of timepoints from the actual size, or ensure those variables always have the expected size?

I think always having the expected size would be the way to go as it allows array concatenation and would be more backwards compatible.
