### ISSUE TITLE
Steadystate solver fails if preequilibration starts in steadystate

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1422]
E.g. preequilibration for the conversion reaction example with initial states [0, 0] fails:

```
    solver.setSensitivityMethod(amici.SensitivityMethod_forward)
    solver.setSensitivityOrder(amici.SensitivityOrder_first)
    model.setSteadyStateSensitivityMode(
        SteadyStateSensitivityMode_simulationFSA)
```

> Steady state sensitivity computation failed due to unsuccessful factorization of RHS Jacobian

preeq_status: [[1 0 0]]

preeq_numsteps [[0 0 0]]

x_ss and sx_ss seem to be set correctly, though.

**Comment by FFroehlich** [comment]
> E.g. preequilibration for the conversion reaction example with initial states [0, 0] fails:
> 
> ```
>     solver.setSensitivityMethod(amici.SensitivityMethod_forward)
>     solver.setSensitivityOrder(amici.SensitivityOrder_first)
>     model.setSteadyStateSensitivityMode(
>         SteadyStateSensitivityMode_simulationFSA)
> ```
> 
> > Steady state sensitivity computation failed due to unsuccessful factorization of RHS Jacobian
> 
> preeq_status: [[1 0 0]]
> 
> preeq_numsteps [[0 0 0]]
> 
> x_ss and sx_ss seem to be set correctly, though.

Is it possible that the Jacobian is singular in that case, which (correctly) prevents computation of sensitivities?

**Comment by paulstapor** [comment]
It is indeed singular, but the fun thing is: Simulation started in steady state. So all the steadystate solver would have to do is just output sx0...

**Comment by FFroehlich** [comment]
> It is indeed singular, but the fun thing is: Simulation started in steady state. So all the steadystate solver would have to do is just output sx0...

Good point!

**Comment by paulstapor** [comment]
Will do on Friday, hopefully. Should be easy to fix
