### ISSUE TITLE
Changelog on rtd documentation

### ISSUE THREAD

**Issue by yannikschaelte** [AMICI-dev/AMICI#1435]
At least a link to the github release notes would be good. If it is somewhere already, I could not find it :)

**Comment by yannikschaelte** [comment]
If one wants, one can also maintain a CHANGELOG.rst in the amici folder (at least with a link), which is the first place developers would look for changelogs I guess.

**Comment by dweindl** [comment]
Agreed. A well structured changelog would be very helpful.
