### ISSUE TITLE
In docs, move About::Contributing to Developer's guide::Contributing

### ISSUE THREAD

**Issue by yannikschaelte** [AMICI-dev/AMICI#1436]
I think a contribution guide and code of conduct makes more sense in the developers section?

**Comment by dweindl** [comment]
As contributions also comprise non-code contributions, and the code of conduct also applies for any discussions here, I'd say it fits in either section. Fine to move, fine to keep. No strong opinion.

**Comment by yannikschaelte** [comment]
ok, then let's just leave it.
