### ISSUE TITLE
LLH reference value for Crauste_CellSystems2017

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#1458]
benchmark_models.yaml reports `190.96398465243203` but AMICI returns `-190.96521897435176` 🤔

**Comment by yannikschaelte** [comment]
Sorry, that was a copy-paste sign error -- confirmed that chi2 (19.66) matches, llh manually computed to -190.9651 matches. No idea why it deviates in the 0.00x, potentially something in amici was changed in the meantime?
