### ISSUE TITLE
Python: sbml2amici fails if SBMl file is altered

### ISSUE THREAD

**Issue by Podde1** [AMICI-dev/AMICI#1483]
**What did you expect to happen?**
For sbml2amici to run. 

**What has happened instead?**
sbml_import.py throws 
> TypeError: 'SBaseList' object is not iterable

when trying to loop over the elements present in the SBML object as in: 
`return [
        reference
        for element in sbml_model.all_elements
        if isinstance(element, sbml.ListOfSpeciesReferences)
        for reference in element
    ]`

**To Reproduce**
*Steps to reproduce the behaviour*
Generate a SBML-file with tellurium [https://tellurium.readthedocs.io/en/latest/](url)
Create SBMLimporter object, declare necessary variables and call sbml2amici

model_file.txt](https://github.com/AMICI-dev/AMICI/files/6246775/model_file.txt)
*Ideally include minimal code examples here*
```
import tellurium as te
import roadrunner 
import os
import amici

r = te.loada('model_file.txt')

SBML_file = 'model_name.xml'

with open(SBML_file, 'w') as f:
     f.write(r.getSBML())

sbml_importer = amici.SbmlImporter(SBML_file)
compilepath = os.getcwd()

sbml_importer.sbml2amici(model_name, compilepath, verbose=False)
```

**AMICI version and system environment**
 - OS and version: Ubuntu 20.04 (on a Windows 10 computer)
 - AMICI interface: Python
 - AMICI version: 0.11.14
 - Additional information: Python 3.8.5

**How to fix**
Do you know how to resolve the problem?
This problem only occurs if the XML file is produced in the same function-call as the amici building process. If the SBML-file already exists there is no problem. Therefore, I am not certain if this is an amici error or if the error comes with the generation of the SBML-file in the same function call.

**Comment by FFroehlich** [comment]
Thanks for reporting this. There is something funny happening in libSBML/libCombine happening here. This is not related to the file itself, but somehow everything what amici expects as libsbml types end up being typecast to libcombine base types that AMICI fails to operate on. I suspect that tellurium uses libcombine and as both have swig exported python interfaces we end up with some kind of namespace collision.

Unfortunately, this is not something we can fix in AMICI :(

**Comment by Podde1** [comment]
I see, thanks for looking into it.
