### ISSUE TITLE
New publications using amici

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#1504]
https://www.sciencedirect.com/science/article/pii/S1096717621000161

https://www.biorxiv.org/content/10.1101/2021.03.25.437053v1.abstract

https://research.wur.nl/en/publications/model-driven-design-of-mycoplasma-as-a-vaccine-chassis

**Comment by FFroehlich** [comment]
Also remove "⁎⁎⁎This Project Has Received Funding from the European Unions Horizon 2020 Research and Innovation Program Under Grant Agreement 675585 (Marie Sklodowska-Curie Itn Symbiosys). The Authors Jap and Lg Are Marie Sklodowska-Curie Early Stage Researchers at Iim-Csic (Spain) and Pse Ltd (Uk) Respectively.”" from https://doi.org/https://doi.org/10.1016/j.ifacol.2018.09.040

**Comment by FFroehlich** [comment]
and "⁎⁎This Research Has Received Funding from the European Unions Horizon 2020 Research and Innovation Program Under Grant Agreement No 686282 (Canpathpro) and the German Ministry of Education and Research (Bmbf) Under the Grant Agreement No 01ZX1310B (Sys-Stomach) and No 01ZX1705A (Income).”" from https://doi.org/10.1016/j.ifacol.2019.12.234

**Comment by jvanhoefer** [comment]
https://joss.theoj.org/papers/10.21105/joss.03215 (we use it for simulating  the examples discussed in the paper...)
