### ISSUE TITLE
new progress bar doesn't show much

### ISSUE THREAD

**Issue by thomassligon** [AMICI-dev/AMICI#1506]
It looks like AMICI now includes a progress bar in the output, but this doesn't provide any information except the % number. Could it be that their is something missing in the formatting?

 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                        | 6/10 [11:15<07:55, 118.87s/it][Warning] AMICI:simulation: AMICI simulation failed:
Steady state computation failed. First run of Newton solver failed: No convergence was achieved. Simulation to steady state failed: No convergence was achieved. Second run of Newton solver failed: No convergence was achieved.
Error occurred in:
stacktrace not available on windows platforms

[Warning] AMICI:simulation: AMICI simulation failed:
Steady state computation failed. First run of Newton solver failed: No convergence was achieved. Simulation to steady state failed: No convergence was achieved. Second run of Newton solver failed: No convergence was achieved.
Error occurred in:
stacktrace not available on windows platforms

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
![Screenshot 2021-05-14 092814](https://user-images.githubusercontent.com/15814751/118236823-d9606780-b496-11eb-8def-8a7d0b2040ed.jpg)
███

**Comment by dweindl** [comment]
Hi Tom, there is no progress bar in AMICI. I guess you are referring to https://github.com/ICB-DCM/pyPESTO/pull/641. Please report at https://github.com/ICB-DCM/pyPESTO/issues.

**Comment by yannikschaelte** [comment]
Hi Tom, yes, this is the pyPESTO progress bar. But actually there should be no further information provided, it is only the fraction of multistarts that have finished.
