### ISSUE TITLE
Pickling the AmiciObjective requires an AMICI installation with HDF5 support

### ISSUE THREAD

**Issue by harshitaojha** [AMICI-dev/AMICI#1533]
https://github.com/ICB-DCM/pyPESTO/issues/703#issuecomment-879406960

**Comment by FFroehlich** [comment]
Thanks for reporting this.

Pickling is implemented in pypesto, so this is not something that can be fixed in amici. Also the dependency is unlikely to go away, so the best thing we can do is provide a more informative error message.

**Comment by harshitaojha** [comment]
Is there no way to fix this error? How to install amici with hdf5 support, except the following method?

1. sudo apt install libhdf5-serial-dev
2. pip install amici
