### ISSUE TITLE
SBML Import : Error with SWIG

### ISSUE THREAD

**Issue by guillaumeba12** [AMICI-dev/AMICI#1547]
**What did you expect to happen?**
I try to import SBML model with 'sbml2amici'

**What has happened instead?**
I have an the following error concerning  swig :
`
Unable to find SWIG executable with default names. Ensure you have SWIG installed, e.g. by `sudo apt install swig` or `brew install swig`. As non-root user, you can install SWIG using https://github.com/AMICI-dev/AMICI/blob/master/scripts/downloadAndBuildSwig.sh, or by following the instructions at http://www.swig.org/Doc4.0/SWIGDocumentation.html#Preface_installation. If was not found despite being installed, set the SWIG environment variable to the full path of the correct executable.
`
I have SWIG installed (version 4.0.2) with 'brew install swig' si I think the problem is on the SWIG environnement variable.

**To Reproduce**
*Steps to reproduce the behavior*
Take a model SBML ('model_steadystate_scaled.xml' for example) and try to import with the minimal code below

*Ideally include minimal code examples here*
```
import libcombine
import libsedml
import amici

sbml_importer = amici.SbmlImporter('model_steadystate_scaled.xml')
sbml_importer.sbml2amici( 'model_test', 'model_dir')
```

**AMICI version and system environment**
 - OS and version: IOS 11.5.2
 - AMICI interface: Python
 - AMICI version : 0.11.18
 - Python version : 3.8
 - SWIG version : 4.0.2

**Comment by stephanmg** [comment]
Are you using a Linux-based OS?

If so, what does `whereis swig` in a terminal return?

**Comment by guillaumeba12** [comment]
I try `whereis swig` in a terminal and it returns nothing.
I attach a screenshot because I have maybe made a mistake :)

![Picture1](https://user-images.githubusercontent.com/90626273/133100614-8ee15b67-cafc-4862-a3c9-82a062f9d86a.png)

**Comment by stephanmg** [comment]
Okay,  this means your `PATH` doesn't contain the `swig` executable, no wonder it fails. Can you try to adjust it?

**Comment by FFroehlich** [comment]
On osx you should be able to locate swig using `which swig`. With a brew installed swig, this should usually return `/usr/local/bin/swig`. If `which swig` does not return anything, you can either add `/usr/local/bin/` (or whever your brew installation is installing to) to your `PATH` environment variable (which would probably be a good idea anyways) or set the SWIG environment variable `/usr/local/bin/swig`. Note that setting those environment variables will be required during installation and model compilation, so you probably want to set them in your `~/.zshrc` profile (assuming you are using the zsh shell).

**Comment by guillaumeba12** [comment]
I don't know how to do it.
Is it the Python Path or an another Path ?

**Comment by stephanmg** [comment]
@guillaumeba12 which Shell are you using? Bash or Zsh? 

Then, will have to set the variable in either of the configuration files for Bash or Zsh.

Information for PATH environment variable: https://en.wikipedia.org/wiki/PATH_(variable)

**Comment by dweindl** [comment]
Hi @guillaumeba12 : It's your shell's `PATH` or `SWIG` environment variable.
Setting one of the two is enough. Note that `PATH` should contain the absolute path to the *directory* in which your swig executable is located, wheres `SWIG` should be the absolute path of your swig executable. 
You can either set it in your shell as described above, or from python via e.g. `os.environ['SWIG'] = '/path/to/swig/executable'`.

**Comment by guillaumeba12** [comment]
Thank you very much it works perfectly :)
I used `which swig` to find the absolute path of my swig executable and I added `os.environ['SWIG'] = '/path/to/swig/executable'` with this path to my python script.

**Comment by stephanmg** [comment]
You can of course make this available globally in your shell configuration file in your home directory if you like.

**Comment by dweindl** [comment]
Resolved. Closing.
