### ISSUE TITLE
steady state simulation fails

### ISSUE THREAD

**Issue by Koppenbrink** [AMICI-dev/AMICI#1570]
**What did you expect to happen?**
I want to use a pre-equilibration condition for parameter estimation and let the system start from a steady-state.

**What has happened instead?**
The pre-equilibration fails, it works fine without pre-equilibration, this is also the case for a parameter vector that looks like it would achieve a steady-state (see MWE)

The error message is the following:

[Warning] AMICI:simulation: AMICI simulation failed:
Steady state computation failed. First run of Newton solver failed: No convergence was achieved. Simulation to steady-state failed. Second run of Newton solver failed: No convergence was achieved.
Error occurred in:
0       0x7f85dfc2fc66 amici::AmiException::AmiException() + 38
1       0x7f85dfc2fd2b amici::AmiException::AmiException(char const*, ...) + 123
2       0x7f85dfb23f1a /home/name/.local/lib/python3.8/site-packages/amici/_amici.cpython-38-x86_64-linux-gnu.so(+0x9ff1a) [0x7f85dfb23f1a]
3       0x7f85dfbd7c29 /home/name/.local/lib/python3.8/site-packages/amici/_amici.cpython-38-x86_64-linux-gnu.so(+0x153c29) [0x7f85dfbd7c29]
4       0x7f85dfbd7ccb amici::SteadystateProblem::workSteadyStateProblem(

**To Reproduce**
I have attached an MWE that first shows the time course of the vector and then uses it for pre-equilibration.

**AMICI version and system environment**
 - OS and version: Ubuntu 20.04.3 LTS 
 - AMICI interface: Python
 - AMICI version: 0.11.18
 - Additional information: Python 3.8.10

Any suggestions on what causes this error are most welcome and thank you in advance

**MWE:**
[MWE.zip](https://github.com/AMICI-dev/AMICI/files/7349129/MWE.zip)

**Comment by FFroehlich** [comment]
Hey @Koppenbrink, thank you for your interest in AMICI. We recently released AMICI 0.11.19 which should give a little bit more informative error messages in case preequilibration fails. Could you test your model with that release?

My suspicion is that you have to play with tolerances a bit. I would recommend *decreasing* integration tolerances via https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setAbsoluteTolerance and https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setRelativeTolerance and *increasing* steady state tolerances via https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setAbsoluteToleranceSteadyState and https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setRelativeToleranceSteadyState
