### ISSUE TITLE
Error on import: _ZSt28__throw_bad_array_new_lengthv

### ISSUE THREAD

**Issue by yannikschaelte** [AMICI-dev/AMICI#1582]
**What did you expect to happen?**

AMICI to work.

**What has happened instead?**

AMICI did not work. On `python -c "import amici"`, after upgrade to Ubuntu 21.10 I got

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yannik/anaconda3/envs/env/lib/python3.8/site-packages/amici/__init__.py", line 125, in <module>
    from . import amici
  File "/home/yannik/anaconda3/envs/env/lib/python3.8/site-packages/amici/amici.py", line 31, in <module>
    from . import _amici
ImportError: /home/yannik/anaconda3/envs/env/lib/python3.8/site-packages/amici/_amici.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```

"Fixed" that after updating/reinstalling `libatlas-base-dev swig` and `libhdf5(-serial)-dev`, but now I still get

```
    """AMICI-generated module for model Zheng_PNAS2012"""
    
    import amici
    
    # Ensure we are binary-compatible, see #556
    if '0.11.19' != amici.__version__:
        raise RuntimeError('Cannot use model Zheng_PNAS2012, generated with AMICI '
                           'version 0.11.19, together with AMICI version'
                           f' {amici.__version__} which is present in your '
                           'PYTHONPATH. Install the AMICI package matching the '
                           'model version or regenerate the model with the AMICI '
                           'currently in your path.')
    
>   from Zheng_PNAS2012._Zheng_PNAS2012 import *
E   ImportError: /home/yannik/pypesto/amici_models/Zheng_PNAS2012/Zheng_PNAS2012/_Zheng_PNAS2012.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

amici_models/Zheng_PNAS2012/Zheng_PNAS2012/__init__.py:14: ImportError
```
when running a model, e.g. in `pytest test/petab/test_amici_objective.py::test_error_leastsquares_with_ssigma
`.

**AMICI version and system environment**
 - OS and version: Ubuntu 21.10
 - AMICI interface: Python
 - AMICI version: 0.11.19
 - Additional information: anaconda Python 3.8.8, gcc 11.2.0, libatlas-base-dev 3.10.3-10ubuntu3, swig 4.0.2-1ubuntu1, libhdf5-dev 1.10.6+repack-5

**Comment by yannikschaelte** [comment]
maybe related https://github.com/cython/cython/issues/4218

**Comment by dweindl** [comment]
Rather a conda problem than an AMICI problem: https://github.com/conda/conda/issues/10757

**Comment by yannikschaelte** [comment]
thanks! it works with system python. then I guess this will work with conda+gcc11 when that conda issue gets fixed. feel free to close, whatever the policy.
