### ISSUE TITLE
Help: How to get sensitivities/gradient? 

### ISSUE THREAD

**Issue by willov** [AMICI-dev/AMICI#1583]
Hello,
we have been looking at the [PyPesto optimization example for optimization using amici](https://pypesto.readthedocs.io/en/latest/example/amici_import.html) and have tried to replicate it with another simple model.

However, we have troubles getting things to work. We are not getting any sensitivities from the model (`rdata[“sllh”] = 0`), and we cannot figure out why. Our parameter set is far from the optimum. 
We have attached a small example with our model and our attempt to get the sensitivities. 

What we have done:
* Build model
* Load/create edata
* Simulated model and checked chi2 (correct compared against original implementation MATLAB)

We have tried to alter the model sensitivities settings, including switching between adjoint and forward, setting values for absolute and/or relative tolerance, and increased the maximum number of iterations, with no success.

We have also tried to optimize using pypesto, but we suspect that our error occurs earlier, so we have not included that code in the attached example. 

Can you see anything that is obviously wrong?
We would be very appreciative of any help getting us in the right direction

Attached files: [amici model test.zip](https://github.com/AMICI-dev/AMICI/files/7498457/amici.model.test.zip)
.

**Comment by dweindl** [comment]
Hi @willov, this seems to be an issue in AMICI. We will have a closer look.

**Comment by willov** [comment]
Thanks for the quick reply. Maybe I should mention that we tested this on 0.11.18, but I just reran the example on 0.11.19, and I get the same behavior. 
I should probably also mention that we converted a set of odes to sbml via yaml2sbml, if that could have an impact in some way.
The intermediate yaml-file is availble here: [M1-yaml.txt](https://github.com/AMICI-dev/AMICI/files/7503785/M1-yaml.txt)

**Comment by dweindl** [comment]
Hi @willov, please update AMICI to v0.11.20, which includes a fix for this issue.

**Comment by willov** [comment]
Great! Thank you!
