### ISSUE TITLE
Compile without sensitivities

### ISSUE THREAD

**Issue by yannikschaelte** [AMICI-dev/AMICI#1613]
**Feature description**
Compile models without (1st/2nd, fw/ad) sensitivity support.

**Motivation/Application**
Sufficient e.g. in many unit tests; derivative-free optimizers. Depending on model size, this may give some compilation speed-up (?).

**Comment by dweindl** [comment]
Sure, why not. -> https://github.com/AMICI-dev/AMICI/pull/1454

**Comment by yannikschaelte** [comment]
oooh wasn't aware of this :heart: so apparently no big speed-up, but worth using anyway.
