### ISSUE TITLE
Enable Model::setStateIsNonNegative for models with conservation laws

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1649]
Not supported so far. See https://github.com/AMICI-dev/AMICI/pull/1648#discussion_r797021260.

**Comment by FFroehlich** [comment]
Supported as far as possible, actual fix for a seperate problem in https://github.com/AMICI-dev/AMICI/commit/3d4975cd7fbffd9be588bc8b8f1e925590b3931f
