### ISSUE TITLE
Add SteadyStateSensitivityMode(s) for Adjoint sensitivities computation in steadyStateProblem

### ISSUE THREAD

**Issue by plakrisenko** [AMICI-dev/AMICI#1670]
**Feature description**
Currently, the approach is to attempt computing the quadrature by solving a linear system and if that didn't work to perform simulation:
https://github.com/AMICI-dev/AMICI/blob/82d2cbb9d00ac9c3746b4e85c0fb1d6ebbff2863/src/steadystateproblem.cpp#L244-L266

If would be convenient to have more control over this and to be able to ensure that only simulation is used for the computation or only Newton's method. E.g. something similar to what is available for forward sensitivities approach: `SteadyStateSensitivityMode.newtonOnly` and `SteadyStateSensitivityMode.simulationFSA`.

**Comment by dweindl** [comment]
Agreed, would be good to have such an option. Current options are also somewhat confusing (`Solver::setSteadyStateSensitivityMode` vs `Solver::setSensitivityMethodPreequilibration` vs `Model::setSteadyStateSensitivityMode`). Happy to have things clearer and more configurable.

**Comment by FFroehlich** [comment]
Agreed, also note that 1SteadyStateSensitivityMode.newtonOnly` and `SteadyStateSensitivityMode.simulationFSA` currently doesn't really provide the fine-grained control over sensitivity computation that one would wish for.

**Comment by thomassligon** [comment]
I have a question about that. In Copasi, when running the steady state task, I can specify "Use Newton", "Use Integration" (or both or neither). In addition, I can specify "Target Criterion" = "Distance" or "Rate" or "Distance and Rate". Is there a setting like this in Amici?

**Comment by dweindl** [comment]
> I have a question about that. In Copasi, when running the steady state task, I can specify "Use Newton", "Use Integration" (or both or neither). In addition, I can specify "Target Criterion" = "Distance" or "Rate" or "Distance and Rate". Is there a setting like this in Amici?

@thomassligon There is [Model.setSteadyStateSensitivityMode()](https://amici.readthedocs.io/en/latest/generated/amici.amici.Model.html#amici.amici.Model.setSteadyStateSensitivityMode) and there is [Solver.setNewtonMaxSteps()](https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setNewtonMaxSteps). There is currently no option corresponding to "Target Criterion".

**Comment by dweindl** [comment]
> * Should we also add  `SteadyStateMode` for steady-state computation? Currently, one can prevent Newton's method application for steady-state computation only by setting `solver.setNewtonMaxSteps(0)`.  There could be three modes:
>   
>   1. 'newtonOnly'
>   2. 'integrationOnly'
>   3. 'both'. This would be the default case and equivalent to the current approach, i.e. Newton's method is tried first and then numerical integration if necessary, then Newton's method from post-integration state if still necessary.
> 
> * Same modes could be used for `SteadyStateSensitivityMode`, but the third option is not applicable with forward sensitivities approach.
>   If it's similar to COPASI, i.e.
>   
>   1. useNewton (True or False)
>   2. useIntegration (True or False)
>      then
>   
>   
>   * forward + `useNewton = True` +  `useIntegration = True`  again doesn't work
>   * forward or adjoint +  `useNewton = False` +  `useIntegration = False` would be equivalent to `solver.SteadyStateSensitivityMode == amici.SensitivityMethod.none` ?

Sounds good to me. Any other opinions? 

(Another alternative would be combining the two options using some flags as in `setSensitivityMethod(adjoint | steadystate_newton | steadystate_simulation)`, but that would break a lot of code.)

**Comment by FFroehlich** [comment]
I think the primary use case for the `integrationOnly` mode would be models with singular RHS Jacobian (J), where we know that we can neither use newtons method to compute the steady state, nor to compute sensitivities. In that situation simulation should be used for both steadystate and sensitivity computation.

In the case of `integrateIfNewtonFails` we are in a tricky situation if newton fails and we continue with simulation, as we do not have initial state sensitivities for the state the newton solver left us in. It may work that we just start sensitivity simulation from initial states, but I am not sure whether convergence to the correct sensitivities is guaranteed, in particular for multistable systems. Thus I would prefer if sensitivity computation via simulation was disabled in that case.

Neither of these settings are correctly handled in the current code.

**Comment by plakrisenko** [comment]
> In the case of `integrateIfNewtonFails` we are in a tricky situation if newton fails and we continue with simulation, as we do not have initial state sensitivities for the state the newton solver left us in. It may work that we just start sensitivity simulation from initial states, but I am not sure whether convergence to the correct sensitivities is guaranteed, in particular for multistable systems. Thus I would prefer if sensitivity computation via simulation was disabled in that case.

I think currently if Newton fails simulations are started from the beginning. If simulation also fails, then the second attempt of applying Newton's method is started from "post-simulation" state.

**Comment by plakrisenko** [comment]
> I think the primary use case for the `integrationOnly` mode would be models with singular RHS Jacobian (J), where we know that we can neither use newtons method to compute the steady state, nor to compute sensitivities. In that situation simulation should be used for both steadystate and sensitivity computation.

Yes, I agree. 
So, if `SensitivityMethod == forward`  and  `SteadyStateSensitivityMode == integrationOnly` it makes sense to switch Newton's method off for both steady state and sensitivities computation.

**Comment by FFroehlich** [comment]
Yes
