### ISSUE TITLE
Events with trigger that has an initial value of False are not supported

### ISSUE THREAD

**Issue by matthiaskoenig** [AMICI-dev/AMICI#1760]
**What did you expect to happen?**
AMICI should support events which trigger at time 0. Often one wants to change values at time zero via events, for instance to set dosing protocols. 

**To Reproduce**
Example attached.
[icg_body_flat_v2.zip](https://github.com/AMICI-dev/AMICI/files/8413334/icg_body_flat_v2.zip)

```
yaml_file: Path = "icg.yaml"
petab_problem = petab.Problem.from_yaml(yaml_file)
amici_model = amici.petab_import.import_petab_problem(petab_problem)
```
results in

```
Traceback (most recent call last):
  File "/home/mkoenig/git/pkdb_models/pkdb_models/models/icg/fit_petab/icg_amici.py", line 28, in <module>
    amici_model = amici.petab_import.import_petab_problem(petab_problem)
  File "/home/mkoenig/envs/pkdb_models/lib/python3.8/site-packages/amici/petab_import.py", line 305, in import_petab_problem
    import_model_sbml(
  File "/home/mkoenig/envs/pkdb_models/lib/python3.8/site-packages/amici/logging.py", line 194, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/mkoenig/envs/pkdb_models/lib/python3.8/site-packages/amici/petab_import.py", line 579, in import_model_sbml
    sbml_importer.sbml2amici(
  File "/home/mkoenig/envs/pkdb_models/lib/python3.8/site-packages/amici/sbml_import.py", line 358, in sbml2amici
    self._process_sbml(constant_parameters)
  File "/home/mkoenig/envs/pkdb_models/lib/python3.8/site-packages/amici/logging.py", line 194, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/mkoenig/envs/pkdb_models/lib/python3.8/site-packages/amici/sbml_import.py", line 406, in _process_sbml
    self.check_support()
  File "/home/mkoenig/envs/pkdb_models/lib/python3.8/site-packages/amici/sbml_import.py", line 469, in check_support
    self.check_event_support()
  File "/home/mkoenig/envs/pkdb_models/lib/python3.8/site-packages/amici/sbml_import.py", line 515, in check_event_support
    raise SBMLException(
amici.sbml_import.SBMLException: Event event_IVDOSE_icg_0 has a trigger that has an initial value of False. This is currently not supported in AMICI.
```

**How to fix**
Read out the `initialValue` flag of the event which sets the initialValue to either `false` or `true`. Evaluate the event trigger at time zero and if it is true fire the event. This is just an event at time 0 which used the initialValue to decide about the transition. AMICI already supports events, this is just the special case of events at time 0 (which is a very typical scenario).

Best Matthias

**Comment by matthiaskoenig** [comment]
Here some context form the SBML specification. As mentioned above the initalValue flag just allows to handle events at t=0.

> An event triggers when the mathematical expression in its Trigger object transitions in value from `false` to `true`. An unanswered question concerns what happens at the start of a simulation: can event triggers make this transition at `t = 0`, where t stands for time? In order to determine whether an event may trigger at t = 0, it is necessary to know what value the Trigger object’s math expression had immediately prior to t = 0. This starting value of the trigger expression is determined by the value of the boolean attribute `initialValue`. A value of `true` means the trigger expression is taken to have the value `true` immediately prior to t = 0. In that case, the trigger cannot transition in value from `false` to `true` at the moment simulation begins (because it has the value `true` both before and after t = 0), and can only make the transition from “false” to “true” sometime after t = 0. Conversely, if `initialValue=false`, then the trigger expression is assumed to start with
the value `false`, and therefore may trigger at t = 0 if the expression evaluates to `true` at that moment.

**Comment by FFroehlich** [comment]
Was not implemented primarily because nobody wanted to use it so far. I can definitely see the utility. 

I wasn't aware of the initial value field, but it sounds like it shouldn't be too difficult to implement support (but we generally allow t0≠0 in amici, but that hopefully doesn't matter).

**Comment by matthiaskoenig** [comment]
Yes, the t0≠0 should not matter. You already have support for events, so this is just a corner case to handle which I would need for most of my applications. 
As far as I understand the status of PETab and AMICI multiple changes at different times are not supported at the moment (see https://github.com/PEtab-dev/PEtab/issues/540). I cannot change parameters/initial conditions at t=0, t=t1, t=t2, .... So the solution is to encode the time dependent condition changes as events. This is what I am currently working on. 

In this context the support for the t=0 events with the initialValue field would be important. E.g. to set in multiple dosing experiments the t=0 dose correctly.

**Comment by FFroehlich** [comment]
The quick workaround would be to directly encode events at t==t0 in the condition table.

I looked at the code and I should be doable to also implement native support. Looks like the sbml testsuite also has a couple of testcases that cover initial assignments for events. Will try to get this in over the weekend.

**Comment by matthiaskoenig** [comment]
@FFroehlich Thanks.

**Comment by matthiaskoenig** [comment]
Hi all, any update on this issue?
Unfortunately most of my models require events which trigger at t=0, e.g., to switch between different model versions or to encode dosing protocols. Supporting initial events would be great.

**Comment by FFroehlich** [comment]
sorry, this fell off my radar. should hopefully be able to fix this on develop this week.

**Comment by FFroehlich** [comment]
Events with initialValues are now supported on the `develop` branch.

**Comment by matthiaskoenig** [comment]
Thanks so much. This is helping me a lot.
 
Sorry for the slow response. I am in the process of evaluating simulation results between roadrunner/COPASI/AMICI for the events models and have to check identity of results. Models are now loading and can be simulated in AMICI.
