### ISSUE TITLE
ReturnData::numstepsB is not set correctly when re-using the same Solver instance

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1813]
First run with a given Solver/Model/ExpData:
`ReturnData::numstepsB = {0, 3, 9, 15, }`
second run with the same inputs:
`ReturnData::numstepsB = {15, 3, 9, 15, }`

Looks as if for the first timepoint, the number of steps from the last timepoint from the previous run are used. 
(Results obtained with adjoint preequilibration enabled, not sure if it matters).

**Comment by dweindl** [comment]
The problem seems to be that `handleDataPointB` is called before solver stats are reset in `setupB`: https://github.com/AMICI-dev/AMICI/blob/e835f94f00c68a93090a7d86a6be97931506ddba/src/backwardproblem.cpp#L79-L80
Just swapping the two lines breaks a number of tests.

**Comment by FFroehlich** [comment]
fixed in #1824

**Comment by dweindl** [comment]
> fixed in #1824

Unfortunately not.

**Comment by dweindl** [comment]
Added a test case in #1841, would be great if you could have a look into that.
