### ISSUE TITLE
Flaky test_models[state_and_parameter_dependent_heavisides] 

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1815]
This test started to fail quite frequently (only on Ubuntu?!). I'd say this only started some time this month. Not sure why.

e.g. https://github.com/AMICI-dev/AMICI/runs/7128465780?check_suite_focus=true
```
>       np.testing.assert_almost_equal(rdata['x'], result_expected_x, decimal=5)
E       AssertionError: 
E       Arrays are not almost equal to 5 decimals
E       
E       Mismatched elements: 2 / 200 (1%)
E       Max absolute difference: 1.85276823e-05
E       Max relative difference: 2.50921502e-06
E        x: array([[0.25   , 1.     ],
E              [0.26813, 1.11736],
E              [0.28758, 1.2485 ],...
E        y: array([[0.25   , 1.     ],
E              [0.26813, 1.11736],
E              [0.28758, 1.2485 ],...
```
https://github.com/AMICI-dev/AMICI/runs/7091811256?check_suite_focus=true (3 failed attempts)

```
>       np.testing.assert_almost_equal(rdata['x'], result_expected_x, decimal=5)
E       AssertionError: 
E       Arrays are not almost equal to 5 decimals
E       
E       Mismatched elements: 2 / 200 (1%)
E       Max absolute difference: 1.85276823e-05
E       Max relative difference: 2.50921502e-06
E        x: array([[0.25   , 1.     ],
E              [0.26813, 1.11736],
E              [0.28758, 1.2485 ],...
E        y: array([[0.25   , 1.     ],
E              [0.26813, 1.11736],
E              [0.28758, 1.2485 ],...
```

As far as I can tell, this test should be deterministic. However, some run between those two [succeeded](https://github.com/AMICI-dev/AMICI/runs/7101088825?check_suite_focus=true).

**Comment by FFroehlich** [comment]
As far as I remember, these tests have been flaky for multiple months.

**Comment by dweindl** [comment]
> As far as I remember, these tests have been flaky for multiple months.

Sure? I only recall https://github.com/AMICI-dev/AMICI/issues/1794 constantly annoying me...

**Comment by dweindl** [comment]
Neither am I able to reproduce this locally, nor do I find any source of randomness. 

:man_shrugging:
