### ISSUE TITLE
importSBML no longer working in current MATLAB version

### ISSUE THREAD

**Issue by thomassligon** [AMICI-dev/AMICI#1875]
In MATLAB Version: 9.8.0.1873465 (R2020a) Update 8 and libSBML 5.19.0. AMICI importSBML fails with error
Error using sym>convertChar (line 1546)
Character vectors and strings in the first argument can only specify a variable or number. To evaluate character
vectors and strings representing symbolic expressions, use 'str2sym'.

As a result, genSSI can no longer import SBML models.

This is related to AMICI issue #234, which was fixed 5 years ago. https://github.com/AMICI-dev/AMICI/issues/234
It is also related (and documented) in the new libSBML issue 274. https://github.com/sbmlteam/libsbml/issues/274

This can be reproduced by running genSSI runExample('BIOMD0000000003')

**Comment by thomassligon** [comment]
A straightforward fix to this is described in https://github.com/sbmlteam/libsbml/issues/274. Is this correct for AMICI?

**Comment by stephanmg** [comment]
> 

Sounds like it.

**Comment by dweindl** [comment]
Hi Tom, we are aware that AMICI only works on MATLAB<R2018a. We don't currently have any plans to rewrite the matlab model import. We would rather drop the Matlab import altogether, once all MATLAB functionality is available from Python. 
Nevertheless, if you manage to make things work with recent Matlab versions, feel free to create a pull request.

**Comment by thomassligon** [comment]
Hi Daniel,
now I am not sure that genSSI is getting SBMLimporter from AMICI. It looks to me like it is being cloned from.https://github.com/ICB-DCM/SBMLimporter, so that would be the place to do it. By the way, do you know which repositories clone SBMimporter from this one? Is it AMICI and genSSI, or a lot more?

**Comment by dweindl** [comment]
Hi Tom, I am not aware of any other projects using that. Maybe @FFroehlich knows more. Considering 1 issue being posted there in 5 years, I'd say it's unlikely that many others are using it.

**Comment by FFroehlich** [comment]
Hmm, not sure. I think the idea was to not duplicate this and AMICI definitely contains the same repository: https://github.com/AMICI-dev/AMICI/tree/master/matlab/SBMLimporter. I don't think any other toolbox uses SBMLimporter.

Even though it looks copy pasted, I think this is actually solved via git submodules (see https://github.com/AMICI-dev/AMICI/blob/57a7b11cc2fb301cf838daefd966830c522643a8/matlab/SBML2AMICI.m)

**Comment by thomassligon** [comment]
Good. I'll close the issue here and open it on ICB-DCM/SBMLimporter.
