### ISSUE TITLE
CI: external test files unavailble

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1886]
These tests regularly fail, because some test data from an unstable URL is required
```
ERROR python/tests/test_conserved_quantities_demartino.py::test_kernel_demartino2014 - urllib.error.URLError: <urlopen error timed out>
ERROR python/tests/test_conserved_quantities_demartino.py::test_fill_demartino2014 - urllib.error.URLError: <urlopen error timed out>
ERROR python/tests/test_conserved_quantities_demartino.py::test_compute_moiety_conservation_laws_demartino2014 - urllib.error.URLError: <urlopen error timed out>
ERROR python/tests/test_conserved_quantities_demartino.py::test_cl_detect_execution_time - urllib.error.URLError: <urlopen error timed out>
```

Tests need to be changed, or the data needs to be uploaded to something more stable.

**Comment by FFroehlich** [comment]
use https://github.com/actions/cache ?

**Comment by dweindl** [comment]
Uploading the respective test files here: 

Supporting Material to https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0100750, © 2014 De Martino et al., used under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

* [test-ecoli-met.txt](https://github.com/AMICI-dev/AMICI/files/11430970/test-ecoli-met.txt)
* [DeMartinoDe2014_test-ecoli.dat.gz](https://github.com/AMICI-dev/AMICI/files/11430971/DeMartinoDe2014_test-ecoli.dat.gz)

Original URLs - meanwhile apparently dead - https://chimera.roma1.infn.it/SYSBIO/test-ecoli.dat.gz, https://chimera.roma1.infn.it/SYSBIO/test-ecoli-met.txt.

**Comment by dweindl** [comment]
Solved
