### ISSUE TITLE
Flaky test `python/tests/test_sbml_import.py::test_likelihoods`

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1895]
Fails way too often. Improve test logic.

**Comment by FFroehlich** [comment]
haven't seen this fail in a while, still relevant or was this fixed?

**Comment by dweindl** [comment]
> haven't seen this fail in a while

True

> still relevant

can be closed for now.

> or was this fixed?

not knowingly. not sure what changed.

**Comment by dweindl** [comment]
There we go again https://github.com/AMICI-dev/AMICI/actions/runs/4022449048/jobs/6912208652
