### ISSUE TITLE
Status code in ReturnData

### ISSUE THREAD

**Issue by aidinbii** [AMICI-dev/AMICI#1905]
Hello, 
Could you please explain what 'status' attribute mean in ReturnData class.
For example, status:  0.0

https://amici.readthedocs.io/en/latest/generated/amici.amici.ReturnData.html

Thank you

**Comment by dweindl** [comment]
Hi @aidinbii, the `ReturnData.status` value should always be one of the following:
https://github.com/AMICI-dev/AMICI/blob/b5177d9ccaa1cc7bf48d8467b1f7b8a3bd81818f/include/amici/defines.h#L69-L81

So, 0.0 would be `amici.AMICI_SUCCESS`, which is what you always want to see. Anything else indicates some kind of error, and some (hopefully informative) message will be printed in that case. This should be documented properly...
