### ISSUE TITLE
Model import slow/not working (sbml2amici)

### ISSUE THREAD

**Issue by ahjanee** [AMICI-dev/AMICI#1997]
Hello,

I'm trying to import a model  that contains quite a lot of parameters and a function that depends on most of these paramters (it's a sum of 100 Gauss peaks and the paramters give peak amplitudes and times). This function is also called when setting up the initial values for the ODEs. Unfortunately,  when importing with
```
sbml_importer.sbml2amici(model_name,
                              model_output_dir,compute_conservation_laws=False, generate_sensitivity_code=False)
```
the model import never finishes. I have confirmed the validity of my model with [Morpheus](https://morpheus.gitlab.io/), where it quickly loads and runs without any issues. When I don't call the function in the initial values, model import is still quite slow but works fine. When I only use a few Gauss peaks, it also works fine.  I'm attaching the model files (.xml and .yml) in case you want to take a look. 

I would be grateful for any help!

EDIT:
After running the importer with verbose=True,  I found it's stuck after this step:
`2023-02-17 10:54:34.825 - amici.ode_export - DEBUG - Finished writing w.cpp                        + (1.15E-03s)`

[model_github.zip](https://github.com/AMICI-dev/AMICI/files/10757904/model_github.zip)

**Comment by FFroehlich** [comment]
Hi @ahjanee, amici by default attempts to simplify model expressions, which can be quite compute intensive for models with complex expressions, such as the one you are looking at. This can be disabled by passing `simplify=None` to `sbml2amici`. I checked and model import for the model you provided finishes in a couple of seconds using this options.

**Comment by ahjanee** [comment]
Thank you! This worked for me.
