### ISSUE TITLE
paper updates

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#2040]
> Fröhlich, Fabian, Luca Gerosa, Jeremy Muhlich, and Peter K. Sorger. 2022. “Mechanistic Model of Mapk Signaling Reveals How Allostery and Rewiring Contribute to Drug Resistance.” bioRxiv. https://doi.org/10.1101/2022.02.17.480899.

now published in MSB

add https://www.sciencedirect.com/science/article/pii/S1755436523000178

> Massonis, Gemma, Alejandro F Villaverde, and Julio R Banga. 2022. “Improving dynamic predictions with ensembles of observable models.” Bioinformatics, November. https://doi.org/10.1093/bioinformatics/btac755.

add https://assets.researchsquare.com/files/rs-2646906/v1/7d855f91-57c0-471b-9491-7321be02e164.pdf?c=1680562558

> Fröhlich, Fabian, and Peter K. Sorger. 2021. “Fides: Reliable Trust-Region Optimization for Parameter Estimation of Ordinary Differential Equation Models.” bioRxiv. https://doi.org/10.1101/2021.05.20.445065.

now published in PLosCB

add https://ieeexplore.ieee.org/abstract/document/9917308

> Erdem, Cemal, Arnab Mutsuddy, Ethan M. Bensman, William B. Dodd, Michael M. Saint-Antoine, Mehdi Bouhaddou, Robert C. Blake, et al. 2021. “A Scalable, Open-Source Implementation of a Large-Scale Mechanistic Model for Single Cell Proliferation and Death Signaling.” bioRxiv. https://doi.org/10.1101/2020.11.09.373407.

now published in Nat Comms

**Comment by dweindl** [comment]
Some are already there. Added all but

> add https://assets.researchsquare.com/files/rs-2646906/v1/7d855f91-57c0-471b-9491-7321be02e164.pdf?c=1680562558

(no bibtex export :|)

in #2040.

**Comment by FFroehlich** [comment]
add https://link.springer.com/protocol/10.1007/978-1-0716-3008-2_3
