### ISSUE TITLE
Periodic piecewise functions

### ISSUE THREAD

**Issue by lcontento** [AMICI-dev/AMICI#2048]
AMICI cannot handle the following model containing a periodic spline (implemented as a periodic piecewise function), while COPASI can. AMICI stops at the end of the first period, with the error
```
2023-04-16 11:33:56.190 - amici.swig_wrappers - DEBUG - [CVODES:CVode:ERR_FAILURE] AMICI ERROR: in module CVODES in function CVode : At t = 1 and h = 9.85551e-09, the error test failed repeatedly or with |h| = hmin. 
2023-04-16 11:33:56.191 - amici.swig_wrappers - ERROR - [FORWARD_FAILURE] AMICI forward simulation failed at t = 1: AMICI failed to integrate the forward problem
```

## Model

https://gist.github.com/lcontento/26b706e5784cc41a05e98003bffd949e

Species: `x`
Parameters: `f`, `f_x_in_fundamental_period`, `y1`, `y2`, `y3`
`y1`, `y2`, `y3` are the spline parameters
`dx/dt = f(t) = spline(f_x_in_fundamental_period(t))`
`f_x_in_fundamental_period(t)` is the strange expression below, which is equal to `fmod(t, 1.0)` [remaps  time to the fundamental period `[0, 1]` to make the spline periodic; there may be better way to do this in MathML, but this is what I found at the time]

```
f_x_in_fundamental_period(t) = ifelse(cos(pi*(2*t-1/2)) < 0, 3, 1) / 4 + atan(tan(pi*(2*t-1/2))) / (2*pi)
```

## Code to reproduce error

```python
import amici
import shutil
import sys
import os
import importlib
import numpy as np

tmpdir = "amici_models"
module = "periodic_splines"
# shutil.rmtree(tmpdir, ignore_errors=True)
amici.SbmlImporter("periodic_spline.xml").sbml2amici(module, tmpdir)
sys.path.insert(0, os.path.abspath(tmpdir))
model = importlib.import_module(module).getModel()

model.setTimepoints(np.linspace(0.0, 3.0, 100))
solver = model.getSolver()
solver.setSensitivityOrder(amici.SensitivityOrder.none)
#solver.setSensitivityMethod(amici.SensitivityMethod.forward)
rdata = amici.runAmiciSimulation(model, solver)
```

**Comment by dweindl** [comment]
Thanks for posting the example. I am able to reproduce the issue as is.

I noticed that `solver.setAbsoluteTolerance(1e-8)` "solves" the issue.

![image](https://user-images.githubusercontent.com/18048784/232300295-7f82f4e6-be7b-4937-bd71-8eba55215e0c.png)

The issue occurs at t=1, which is where the event should trigger. I am not very familiar with whole event handling, so just guessing. Could it be that the event triggers slightly too late and solver chokes on that discontinuity?

`root.cpp`
```
    root[0] = std::sin(2*amici::pi*t);
    root[1] = -std::sin(2*amici::pi*t);
    root[2] = -0.75*Heaviside_0 + 0.25*amici::heaviside(std::cos(amici::pi*(2*t - 1.0/2.0)), 1.0/2.0) + (1.0/2.0)*std::atan(std::tan(amici::pi*(2*t - 1.0/2.0)))/amici::pi + 0.41666666666666669;
    root[3] = 0.75*Heaviside_0 - 0.25*amici::heaviside(std::cos(amici::pi*(2*t - 1.0/2.0)), 1.0/2.0) - 1.0/2.0*std::atan(std::tan(amici::pi*(2*t - 1.0/2.0)))/amici::pi - 0.41666666666666669;
    root[4] = -0.75*Heaviside_0 + 0.25*amici::heaviside(std::cos(amici::pi*(2*t - 1.0/2.0)), 1.0/2.0) + (1.0/2.0)*std::atan(std::tan(amici::pi*(2*t - 1.0/2.0)))/amici::pi + 0.08333333333333337;
    root[5] = 0.75*Heaviside_0 - 0.25*amici::heaviside(std::cos(amici::pi*(2*t - 1.0/2.0)), 1.0/2.0) - 1.0/2.0*std::atan(std::tan(amici::pi*(2*t - 1.0/2.0)))/amici::pi - 0.08333333333333337;
```

Maybe related to rounding issues in the last summand? Maybe fixable by using rationals instead of floats in sympy, or keeping sympy from evaluating the trigger function?

CC @FFroehlich

**Comment by dweindl** [comment]
> [...] strange expression below, which is equal to `fmod(t, 1.0)` [remaps time to the fundamental period `[0, 1]` to make the spline periodic; there may be better way to do this in MathML, but this is what I found at the time]

MathML supports modulo via [`<rem/>`](https://www.w3.org/TR/MathML2/chapter4.html#contm.rem), sympy via `sympy.Mod`. Does that work any better? (I am not sure if `rem` is handled appropriately in terms of events in AMICI, or is understood at all).

**Comment by lcontento** [comment]
Yes, but `<rem/>` is not supported in SBML Level 2. It seems to be in Level 3, but both COPASI and AMICI use Level 2 (not sure if that can be changed for AMICI?)

**Comment by lcontento** [comment]
Why are there events involved? Aren't piecewise functions implemented with a simple `if else` statement?

**Comment by dweindl** [comment]
> > MathML supports modulo via `<rem/>`, sympy via `sympy.Mod`. Does that work any better? (I am not sure if rem is handled appropriately in terms of events in AMICI, or is understood at all).
> 
> Yes, but `<rem/>` is not supported in SBML Level 2. 

True

> It seems to be in Level 3, but both COPASI and AMICI use Level 2 (not sure if that can be changed for AMICI?)

AMICI supports level 3

> Why are there events involved? Aren't piecewise functions implemented with a simple `if else` statement?

Because piecewise functions may introduce discontinuities. For the spline case, or any other continuous case, this could be handled more efficiently, but there is no such distinction yet.

**Comment by lcontento** [comment]
> AMICI supports level 3 (to the usual extent ...)

```
2023-04-16 13:10:38.907 - amici.sbml_import - ERROR - libSBML MathML consistency (Error): The only permitted MathML 2.0 elements in SBML Level 2 are the following: <cn>, <ci>, <csymbol>, <sep>, <apply>, <piecewise>, <piece>, <otherwise>, <eq>, <neq>, <gt>, <lt>, <geq>, <leq>, <plus>, <minus>, <times>, <divide>, <power>, <root>, <abs>, <exp>, <ln>, <log>, <floor>, <ceiling>, <factorial>, <and>, <or>, <xor>, <not>, <degree>, <bvar>, <logbase>, <sin>, <cos>, <tan>, <sec>, <csc>, <cot>, <sinh>, <cosh>, <tanh>, <sech>, <csch>, <coth>, <arcsin>, <arccos>, <arctan>, <arcsec>, <arccsc>, <arccot>, <arcsinh>, <arccosh>, <arctanh>, <arcsech>, <arccsch>, <arccoth>, <true>, <false>, <notanumber>, <pi>, <infinity>, <exponentiale>, <semantics>, <annotation>, and <annotation-xml>. SBML L3V2 added <implies>, <max>, <min>, <rem> and <quotient>.
Reference: L2V5 Section 3.4.1
 <rem> is not valid in SBML Level 2 Version 5.
```

**Comment by lcontento** [comment]
> Because piecewise functions may introduce discontinuities. For the continuous spline case, or any other continuous case, this could be handled more efficiently, but there is no such distinction yet.

Is this something new (which in my case means after summer 2020)? Because I vaguely remember looking at the code generated from piecewise functions at the time and seeing `if else` statements. If this changed, then this may be the deeper reason why the example I posted now works and did not in summer 2020.

**Comment by dweindl** [comment]
> > AMICI supports level 3 (to the usual extent ...)
> 
> ```
> 2023-04-16 13:10:38.907 - amici.sbml_import - ERROR - libSBML MathML consistency (Error): The only permitted MathML 2.0 elements in SBML Level 2 are the following: <cn>, <ci>, <csymbol>, <sep>, <apply>, <piecewise>, <piece>, <otherwise>, <eq>, <neq>, <gt>, <lt>, <geq>, <leq>, <plus>, <minus>, <times>, <divide>, <power>, <root>, <abs>, <exp>, <ln>, <log>, <floor>, <ceiling>, <factorial>, <and>, <or>, <xor>, <not>, <degree>, <bvar>, <logbase>, <sin>, <cos>, <tan>, <sec>, <csc>, <cot>, <sinh>, <cosh>, <tanh>, <sech>, <csch>, <coth>, <arcsin>, <arccos>, <arctan>, <arcsec>, <arccsc>, <arccot>, <arcsinh>, <arccosh>, <arctanh>, <arcsech>, <arccsch>, <arccoth>, <true>, <false>, <notanumber>, <pi>, <infinity>, <exponentiale>, <semantics>, <annotation>, and <annotation-xml>. SBML L3V2 added <implies>, <max>, <min>, <rem> and <quotient>.
> Reference: L2V5 Section 3.4.1
>  <rem> is not valid in SBML Level 2 Version 5.
> ```

Yes. AMICI supports SBML L3 in an SBML L3 model, but you can't use L3 syntax in an L2 model. I guess your model still had `<sbml xmlns="http://www.sbml.org/sbml/level2/version5" level="2" version="5">` in there.

**Comment by dweindl** [comment]
> > Because piecewise functions may introduce discontinuities. For the continuous spline case, or any other continuous case, this could be handled more efficiently, but there is no such distinction yet.
> 
> Is this something new (which in my case means after summer 2020)? Because I vaguely remember looking at the code generated from piecewise functions at the time and seeing `if else` statements. If this changed, then this may be the deeper reason why the example I posted now works and did not in summer 2020.

Yup. https://github.com/AMICI-dev/AMICI/pull/1594

**Comment by lcontento** [comment]
> > > AMICI supports level 3 (to the usual extent ...)
> > 
> > 
> > ```
> > 2023-04-16 13:10:38.907 - amici.sbml_import - ERROR - libSBML MathML consistency (Error): The only permitted MathML 2.0 elements in SBML Level 2 are the following: <cn>, <ci>, <csymbol>, <sep>, <apply>, <piecewise>, <piece>, <otherwise>, <eq>, <neq>, <gt>, <lt>, <geq>, <leq>, <plus>, <minus>, <times>, <divide>, <power>, <root>, <abs>, <exp>, <ln>, <log>, <floor>, <ceiling>, <factorial>, <and>, <or>, <xor>, <not>, <degree>, <bvar>, <logbase>, <sin>, <cos>, <tan>, <sec>, <csc>, <cot>, <sinh>, <cosh>, <tanh>, <sech>, <csch>, <coth>, <arcsin>, <arccos>, <arctan>, <arcsec>, <arccsc>, <arccot>, <arcsinh>, <arccosh>, <arctanh>, <arcsech>, <arccsch>, <arccoth>, <true>, <false>, <notanumber>, <pi>, <infinity>, <exponentiale>, <semantics>, <annotation>, and <annotation-xml>. SBML L3V2 added <implies>, <max>, <min>, <rem> and <quotient>.
> > Reference: L2V5 Section 3.4.1
> >  <rem> is not valid in SBML Level 2 Version 5.
> > ```
> 
> Yes. AMICI supports SBML L3 in an SBML L3 model, but you can't use L3 syntax in an L2 model. I guess your model still had `<sbml xmlns="http://www.sbml.org/sbml/level2/version5" level="2" version="5">` in there.

Yes, you are right. I just copy and paste the first lines without ever looking at them. Then maybe `<rem>` could be an alternative (if COPASI et al support it).

**Comment by FFroehlich** [comment]
> > > > AMICI supports level 3 (to the usual extent ...)
> > > 
> > > 
> > > ```
> > > 2023-04-16 13:10:38.907 - amici.sbml_import - ERROR - libSBML MathML consistency (Error): The only permitted MathML 2.0 elements in SBML Level 2 are the following: <cn>, <ci>, <csymbol>, <sep>, <apply>, <piecewise>, <piece>, <otherwise>, <eq>, <neq>, <gt>, <lt>, <geq>, <leq>, <plus>, <minus>, <times>, <divide>, <power>, <root>, <abs>, <exp>, <ln>, <log>, <floor>, <ceiling>, <factorial>, <and>, <or>, <xor>, <not>, <degree>, <bvar>, <logbase>, <sin>, <cos>, <tan>, <sec>, <csc>, <cot>, <sinh>, <cosh>, <tanh>, <sech>, <csch>, <coth>, <arcsin>, <arccos>, <arctan>, <arcsec>, <arccsc>, <arccot>, <arcsinh>, <arccosh>, <arctanh>, <arcsech>, <arccsch>, <arccoth>, <true>, <false>, <notanumber>, <pi>, <infinity>, <exponentiale>, <semantics>, <annotation>, and <annotation-xml>. SBML L3V2 added <implies>, <max>, <min>, <rem> and <quotient>.
> > > Reference: L2V5 Section 3.4.1
> > >  <rem> is not valid in SBML Level 2 Version 5.
> > > ```
> > 
> > 
> > Yes. AMICI supports SBML L3 in an SBML L3 model, but you can't use L3 syntax in an L2 model. I guess your model still had `<sbml xmlns="http://www.sbml.org/sbml/level2/version5" level="2" version="5">` in there.
> 
> Yes, you are right. I just copy and paste the first lines without ever looking at them. Then maybe `<rem>` could be an alternative (if COPASI et al support it).

not sure whether we support `<rem>`, not continuous after all.

**Comment by FFroehlich** [comment]
> Thanks for posting the example. I am able to reproduce the issue as is.
> 
> I noticed that `solver.setAbsoluteTolerance(1e-8)` "solves" the issue.
> 
> ![image](https://user-images.githubusercontent.com/18048784/232300295-7f82f4e6-be7b-4937-bd71-8eba55215e0c.png)
> 
> The issue occurs at t=1, which is where the event should trigger. I am not very familiar with whole event handling, so just guessing. Could it be that the event triggers slightly too late and solver chokes on that discontinuity?
> 
> `root.cpp`
> 
> ```
>     root[0] = std::sin(2*amici::pi*t);
>     root[1] = -std::sin(2*amici::pi*t);
>     root[2] = -0.75*Heaviside_0 + 0.25*amici::heaviside(std::cos(amici::pi*(2*t - 1.0/2.0)), 1.0/2.0) + (1.0/2.0)*std::atan(std::tan(amici::pi*(2*t - 1.0/2.0)))/amici::pi + 0.41666666666666669;
>     root[3] = 0.75*Heaviside_0 - 0.25*amici::heaviside(std::cos(amici::pi*(2*t - 1.0/2.0)), 1.0/2.0) - 1.0/2.0*std::atan(std::tan(amici::pi*(2*t - 1.0/2.0)))/amici::pi - 0.41666666666666669;
>     root[4] = -0.75*Heaviside_0 + 0.25*amici::heaviside(std::cos(amici::pi*(2*t - 1.0/2.0)), 1.0/2.0) + (1.0/2.0)*std::atan(std::tan(amici::pi*(2*t - 1.0/2.0)))/amici::pi + 0.08333333333333337;
>     root[5] = 0.75*Heaviside_0 - 0.25*amici::heaviside(std::cos(amici::pi*(2*t - 1.0/2.0)), 1.0/2.0) - 1.0/2.0*std::atan(std::tan(amici::pi*(2*t - 1.0/2.0)))/amici::pi - 0.08333333333333337;
> ```
> 
> Maybe related to rounding issues in the last summand? Maybe fixable by using rationals instead of floats in sympy, or keeping sympy from evaluating the trigger function?
> 
> CC @FFroehlich

Depends on what the error is if other tolerances are used. But agree, probably related to tolerances that are insufficient for rootfinding to work reliably.
