### ISSUE TITLE
How to set initial value for species for simple forward simulation?

### ISSUE THREAD

**Issue by matthiaskoenig** [AMICI-dev/AMICI#2059]
Hi all,
It seems that COPASI, roadrunner and AMICI give different simulations for certain forward simulations. 
I wanted to debug this and run simple timecourse simulations with AMICI to compare the numerical results between different solvers.
To run the simulations I have to set initial parameter values and initial values for species (and probably also compartments).

I could not figure out how to set initial species values for a forward simulation in AMICI. Please see my example code below. How can I set the initial value for the species `IVDOSE_icg`? Full example with model attached
[amicitesting.zip](https://github.com/AMICI-dev/AMICI/files/11330248/amicitesting.zip)

```python
"""AMICI example simulation"""
from pathlib import Path
import amici
import numpy as np

mid = "icg_sd"
base_path: Path = Path(__file__).parent
model_dir = base_path / mid
model_path = base_path / f"{mid}.xml"

sbml_importer = amici.SbmlImporter(model_path)
sbml_importer.sbml2amici(mid, model_dir)

# load the model module
model_module = amici.import_model_module(mid, model_dir)

# instantiate model
model = model_module.getModel()

# instantiate solver
solver = model.getSolver()

# changes
changes = {
    "BW": 83.4,  # parameter initial condition
    "Ri_icg": 0.0,  # parameter initial condition
    "IVDOSE_icg": 41.7,  # species initial condition
}

for key, value in changes.items():

    try:
        # set parameters
        model.setParameterById(key, value)
        print(f"{key} = {value}")
    except RuntimeError as err:
        # FIXME: how to set the initial value of the state species IVDOSE_icg ??
        raise err

# set timepoints
t = np.linspace(0, 10, num=11)
model.setTimepoints(t)

# simulation
rdata = amici.runAmiciSimulation(model, solver)
print(rdata)

```

Output
```bash
BW = 83.4
Ri_icg = 0.0
Traceback (most recent call last):
  File "/home/mkoenig/git/sbmlsim/src/sbmlsim/comparison/amicitesting/example_amici.py", line 38, in <module>
    raise err
  File "/home/mkoenig/git/sbmlsim/src/sbmlsim/comparison/amicitesting/example_amici.py", line 34, in <module>
    model.setParameterById(key, value)
  File "/home/mkoenig/.virtualenvs/sbmlsim/lib/python3.10/site-packages/amici/amici.py", line 1896, in setParameterById
    return _amici.ModelPtr_setParameterById(self, *args)
RuntimeError: Could not find parameter with specified id

```
Also how would I set initial values for compartments?
Thanks for any help
Best Matthias

**Comment by FFroehlich** [comment]
Hi Matthias,

unfortunately there currently are no functions to get/set the initial conditions for individual states, only for all states at once ([getInitialStates](https://amici.readthedocs.io/en/latest/generated/amici.amici.html#amici.amici.Model.setInitialStates), [getInitialStates](https://amici.readthedocs.io/en/latest/generated/amici.amici.html#amici.amici.Model.getInitialStates)).

So you would need to do something along the lines of

```
x0 = np.asarray(model.getInitialStates())
for key, value in changes.items():
    x0[model.getStateIds().index(key)] = value
model.setInitialStates(x0)
```

**Comment by dweindl** [comment]
> Also how would I set initial values for compartments?

Compartment sizes are hard-coded. If you want to change them in AMICI, you will have to add an initial-size-parameter and an initial assignment to the respective compartment. (In the case of variable-size compartments, Fabian's answer applies.)

**Comment by dweindl** [comment]
Hi Matthias, it seems `model.setInitialStates(x0)` is missing in your code, isn't it?

**Comment by matthiaskoenig** [comment]
Top thanks.
