### ISSUE TITLE
`preeq_wrms` and `posteq_wrms` values are zero with FSA

### ISSUE THREAD

**Issue by plakrisenko** [AMICI-dev/AMICI#2066]
The values should be equal to "weighted root-mean-square of the rhs when steady state was reached".

I get values equal to "0.0" in case 
`solver.setSensitivityOrder(amici.SensitivityOrder_first)`
`amici_solver.setSensitivityMethod(SensitivityMethod.forward)`
`amici_solver.setNewtonMaxSteps(0)`
`amici_model.setSteadyStateSensitivityMode(amici.SteadyStateSensitivityMode.integrationOnly)`.
However, in case I use `SensitivityMethod.adjoint` I get values different from "0.0", e.g. "0.91".

 - AMICI version: 0.16.1
 
 I suppose, it's related to the line here
 https://github.com/AMICI-dev/AMICI/blob/master/src/steadystateproblem.cpp#L711
 
 I think, in the end the output of `getWrmsFSA` is saved to `preeq_wrms` (or `posteq_wrms`), not output of `getWrms`.  Not sure why it's always "0.0", though. I tried with different tolerances, fsa tolerances.

**Comment by dweindl** [comment]
> I think, in the end the output of `getWrmsFSA` is saved to `preeq_wrms` (or `posteq_wrms`), not output of `getWrms`.

Correct.

Agreed that this doesn't match the current documentation at
https://github.com/AMICI-dev/AMICI/blob/1a99308c23a40a4175aa6b31f01c131f3ee4876e/include/amici/rdata.h#L332-L336
or https://github.com/AMICI-dev/AMICI/blob/1a99308c23a40a4175aa6b31f01c131f3ee4876e/include/amici/rdata.h#L343-L347
