### ISSUE TITLE
0.17.1 install fails

### ISSUE THREAD

**Issue by Mjvolk3** [AMICI-dev/AMICI#2103]
**What did you expect to happen?**

I am using a conda environment on a linux machine to install amici. Amici install fails with the [#include <cblas> error](https://github.com/AMICI-dev/AMICI/blob/81d32e785af4a70e72d458196d709e1d18563556/documentation/python_faq.rst#id1) (First Q in the FAQ)

**What has happened instead?**

I expected a proper installation of Amici. The reproduction code below works with v0.16.1.

**To Reproduce**

```bash
conda create --yes -n env pip python=3.10
conda activate env
conda install --yes -c conda-forge swig hdf5 openblas
export BLAS_LIBS=-lopenblas
pip install --no-cache-dir amici==0.17.1 # also fails with 0.17.0
```
**Note**: This works with v0.16.1

**AMICI version and system environment**
 - OS and version: [e.g. Ubuntu, iOS, Windows]

```bash
%lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.6 (Ootpa)
Release:        8.6
Codename:       Ootpa

```
 - AMICI interface: [e.g. Python, Matlab, C++]
python

 - AMICI version:
 0.17.1

 - Additional information: Compiler name and version used, Python/Matlab version, ...

GCC 11.2.0 compiler + OpenMPI
More information about the machine can be found here [NCSA Delta](https://wiki.ncsa.illinois.edu/display/DSC/Delta+User+Guide).

**How to fix**
Do you know how to resolve the problem?

No. I reverted to the previous version that works

Can you submit a pull request?

No. I don't know the solution.

**Comment by dweindl** [comment]
Hi @Mjvolk3, in v0.17.0 we reorganized how the AMICI extension is built. This involved changing/removing some of the dependency handling. Before, we had some hard-coded paths to look for BLAS headers, but this is not very sustainable, and potentially incompatible with conda environments.

That means, you will now have to set `BLAS_CFLAGS=-I/absolute/path/of/cblas.h/containing/directory` (in addition to `BLAS_LIBS`). You can get that path either from searching `cblas.h` inside your conda environment, or if you have a running amici<0.17.0 installation, from `python -c "from amici.setuptools import get_blas_config; print(get_blas_config()['include_dirs'])"` .

I will consider using CMake to try to find some BLAS automatically, but last time I tried, this had other issues...

**Comment by dweindl** [comment]
P.S.: Does `pip3 install -ve git+https://github.com/AMICI-dev/amici.git@find_blas#egg=amici\&subdirectory=python/sdist` work for you, after unsetting both `BLAS_LIBS` and `BLAS_CFLAGS`? (#2104)
