### ISSUE TITLE
AMICI installation on Windows

### ISSUE THREAD

**Issue by anavalinhas** [AMICI-dev/AMICI#2151]
Hi there, 

I'm trying to install the amici package on windows using Microsoft Visual Studio. I am following the instructions [here](https://amici.readthedocs.io/en/latest/python_installation.html).

I have installed SWIG v4.1.1 and followed the steps under OpenBLAS to build OpenBLAS binaries from scratch. I've made all the changes in PATH variables as necessary.

I have copied the error message onto a separate file bellow. I would really appreciate any help/suggestions you may have.

[amici_install_windows_error_file.txt](https://github.com/AMICI-dev/AMICI/files/12174802/amici_install_windows_error_file.txt)

**Comment by dweindl** [comment]
Hi @anavalinhas, thanks for the detailed report. Could you please try if changing `/LIBPATH:C:/BLAS/OpenBLAS/lib openblas.lib` to `-LIBPATH:C:/BLAS/OpenBLAS/lib openblas.lib` helps? (in the `BLAS_LIBS` environment variable or in the registry, depending on which option you chose initially)

**Comment by anavalinhas** [comment]
@dweindl I have modified the BLAS_LIBS variable as suggested and I get another error. The system fails to find 'unistd.h'. I've attached a file with the full error message bellow for reference.

[amici_install_windows_error_file_1.txt](https://github.com/AMICI-dev/AMICI/files/12193116/amici_install_windows_error_file_1.txt)

**Comment by dweindl** [comment]
Great, so the first issue is resolved, I will update the documentation accordingly.

Regarding `amici\src\hdf5.cpp(30): fatal error C1083: Cannot open include file: 'unistd.h': No 
such file or directory`: 

It seems like so far, nobody had HDF5 available on Windows and this issue never surfaced. 

If you don't need HDF5 support, you can try installing AMICI after setting an environment variable `AMICI_TRY_ENABLE_HDF5=OFF` - this was only introduced recently and is not yet available on pypi:

* if you have a bash-like shell:
`AMICI_TRY_ENABLE_HDF5=OFF pip3 install -e git+https://github.com/AMICI-dev/amici.git@develop#egg=amici\&subdirectory=python/sdist`
* with cmd.exe, something like
  ```
  set AMICI_TRY_ENABLE_HDF5=OFF
  pip3 install -e git+https://github.com/AMICI-dev/amici.git@develop#egg=amici\&subdirectory=python/sdist
  ```
  
 I will check what `unistd.h` is used for, and will try to find an alternative for windows.

**Comment by dweindl** [comment]
@anavalinhas : You can first try `pip3 install -e git+https://github.com/AMICI-dev/amici.git@no_unistd#egg=amici\&subdirectory=python/sdist`. If that doesn't work, please try my suggestions from the previous post.

**Comment by anavalinhas** [comment]
@dweindl I have run `pip3 install -ve git+https://github.com/AMICI-dev/amici.git@no_unistd#egg=amici\&subdirectory=python/sdist` without success. I've then run your suggestion above `set AMICI_TRY_ENABLE_HDF5=OFF
pip3 install -ve git+https://github.com/AMICI-dev/amici.git@develop#egg=amici\&subdirectory=python/sdist` (I ran both suggestions directly on the terminal of Pycharm). The final error message I got is in the file in attachment.

[amici_install_windows_error_file_2.txt](https://github.com/AMICI-dev/AMICI/files/12194980/amici_install_windows_error_file_2.txt)

**Comment by dweindl** [comment]
That looks like an independent issue with editable installations on Windows :confused: 

@anavalinhas How about `pip3 install -v git+https://github.com/AMICI-dev/amici.git@no_unistd#egg=amici\&subdirectory=python/sdist`? (without the `-e` from before)
Or `set AMICI_TRY_ENABLE_HDF5=OFF pip3 install -v git+https://github.com/AMICI-dev/amici.git@develop#egg=amici\&subdirectory=python/sdist`?

**Comment by anavalinhas** [comment]
@dweindl I've tried both suggestions and unfortunatelly I get a similar error 'ValueError: Directory 'C:\Users\ttval\AppData\Local\Temp\pip-install-5u7md00q\amici_dc6f87e221c04c64ad3a389d02c8c56b\python\sdist\amici\ThirdParty\SuiteSparse\SuiteSparse_config' doe
s not exist
'. Do you have any recommendations on how to start troubleshooting this error? Thank you for your help with all this so far! 😊

**Comment by stephanmg** [comment]
Does the folder really not exist or is it some path issue?

**Comment by dweindl** [comment]
Hm, then let's try the less convenient way, @anavalinhas:

1. download and unpack https://github.com/AMICI-dev/AMICI/archive/refs/heads/no_unistd.zip
2. `pip install build`
3. change into the unpacked archive from step 1 then `python -m build -s python/sdist/`
4. `pip install -v python/sdist/dist/amici-0.18.1.tar.gz`

**Comment by dweindl** [comment]
> Do you have any recommendations on how to start troubleshooting this error?

Oh, I think this might be about not having enabled symlinks on Windows. This is not required when installing from pypi, but when installing from the repository. So probably my previous instructions will also fail. I will upload a source distribution shortly, to skip steps 1--3.

**Comment by dweindl** [comment]
@anavalinhas:

1. download [amici-0.18.1.tar.gz](https://github.com/AMICI-dev/AMICI/files/12195340/amici-0.18.1.tar.gz)
2. `pip install -v amici-0.18.1.tar.gz`

**Comment by anavalinhas** [comment]
Hi @dweindl, I've first ran 'pip install -v amici-0.18.1.tar.gz' without success, followed by 'set AMICI_TRY_ENABLE_HDF5=OFF' and 'pip install -v amici-0.18.1.tar.gz'. I got an error message that I included in attachment. 

There is reference to swig in the error message. For context (and in case I didn't set system variables properly) I've created the python environment variables for swig as suggested in their website [here](https://www.swig.org/Doc1.3/Windows.html#Windows_examples) having in account the python version I'm using.

[amici_install_windows_error_file_3.txt](https://github.com/AMICI-dev/AMICI/files/12209699/amici_install_windows_error_file_3.txt)

**Comment by dweindl** [comment]
Thanks for the update @anavalinhas. On the positive side, the previous issues are resolved.

(At least) two problems remain, let's see if we can solve at least one: 
* For some reason, `AMICI_TRY_ENABLE_HDF5=OFF` didn't do what it was supposed to do. It works on Linux, not sure what might go wrong on Windows. I created a package where HDF5 is disabled by default: 
Please download [amici-nohdf5-0.18.1.tar.gz](https://github.com/AMICI-dev/AMICI/files/12209800/amici-nohdf5-0.18.1.tar.gz) and run `pip install -v amici-nohdf5-0.18.1.tar.gz`
 
* Linking issues with HDF5 on Windows. I don't know if MSVC requires a different order. Just one more attempt here (now uses the `HDF5::HDF5` instead of the individual ones):
  Please download [amici-HDF5-0.18.1.tar.gz](https://github.com/AMICI-dev/AMICI/files/12209806/amici-HDF5-0.18.1.tar.gz) and run `pip install -v amici-HDF5-0.18.1.tar.gz`

**Comment by anavalinhas** [comment]
Hi @dweindl the first bullet point worked! Many thanks for all your help 😊!
