### ISSUE TITLE
INTEL MKL ERROR on Google Colab when running AMICI

### ISSUE THREAD

**Issue by lmriccardo** [AMICI-dev/AMICI#2176]
I'm trying to run amici on google colab, but it happens that I obtain the following errors:

```
INTEL MKL ERROR: /lib/x86_64-linux-gnu/libmkl_avx2.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

When running this code:

```Python
import os

import amici
import benchmark_models_petab as models
import matplotlib.pyplot as plt
import numpy as np
import petab

import pypesto
import pypesto.optimize as optimize
import pypesto.petab
import pypesto.visualize as visualize

model_name = "Boehm_JProteomeRes2014"
yaml_config = os.path.join(models.MODELS_DIR, model_name, model_name + ".yaml")
petab_problem = petab.Problem.from_yaml(yaml_config)

importer = pypesto.petab.PetabImporter(petab_problem)
model = importer.create_model()

import libsbml
converter_config = libsbml.SBMLLocalParameterConverter().getDefaultProperties()
petab_problem.sbml_document.convert(converter_config)
obj = importer.create_objective()

ret = obj(
    petab_problem.x_nominal_scaled,
    mode="mode_fun",
    sensi_orders=(0, 1),
    return_dict=True,
)
print(ret)
```

This is a code I found for searching "Pypesto on Google Colab". 

I have tried to set the environment variable.

```Python
import os
os.environ['LD_PRELOAD'] = "/usr/lib/x86_64-linux-gnu/libmkl_def.so:/usr/lib/x86_64-linux-gnu/libmkl_avx2.so:/usr/lib/x86_64-linux-gnu/libmkl_core.so:/usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so:/usr/lib/x86_64-linux-gnu/libmkl_intel_thread.so:/usr/lib/x86_64-linux-gnu/libiomp5.so"
```

As suggested [here](https://bugs.launchpad.net/ubuntu/+source/intel-mkl/+bug/1947626). But nothing is working as expected.

What is happening here? Anyone can help? Thank you!!

**Comment by stephanmg** [comment]
Ah okay, please combine the `os.environ` part and the main script in your first code listing in ONE script. I think thad should work...

**Comment by lmriccardo** [comment]
It does not work either.

**Comment by lmriccardo** [comment]
I cannot do something like this in google colab. They are Jupyter notebook. 
If I run AMICI in my host machine It works as intended. However, in colab it does not.

**Comment by lmriccardo** [comment]
This one: [link](https://colab.research.google.com/github/icb-dcm/pypesto/blob/main/doc/example/petab_import.ipynb). If you can try and tell me if there is the same error.

**Comment by stephanmg** [comment]
Thanks for providing the link. I tried to execute it, but for me already installation of AMICI fails. I will try to have a look into this... maybe @dweindl can also have a look into this.

**Comment by lmriccardo** [comment]
Make sure in the first cell of the notebook to remove the commend from the command `!apt install libatlas-base-dev swig`

**Comment by stephanmg** [comment]
Okay, this works for me, I get the same error (Expected).

So two things:
1) Notebook has to be amended
2) MKL error has to be investigated

Right now I can do only 1) for 2) I will need some help from AMICI dev team. I will come back to you when the issue could be resolved.

**Comment by lmriccardo** [comment]
Okay thank you. I really would like to execute AMICI and PyPESTO on colab. My home workstation does not provide the same computational power you know ...

**Comment by dweindl** [comment]
Hi, I'll try to have a look at it next week.

**Comment by dweindl** [comment]
HI @lmriccardo, do you need the INTEL MKL specifically? If not, uninstalling that should do the trick:
```
!apt remove intel-mkl libmkl-*
!apt install libatlas-base-dev swig
```

As already noted, the LD_PRELOAD won't  work. That would have to be set before launching python/jupyter. 
If MKL is required, I'll have to dig deeper why those other MKL libraries aren't found automatically.

**Comment by lmriccardo** [comment]
@dweindl It worked. Thank you very much!! I really don't know what is Intel MKL. In my home desktop I have AMD processor, so seeing that error quite scared me. However, now it works as usual.

I will close this Issue. Thank you.
