### ISSUE TITLE
NaNs in model expressions with DiracDelta due to unfortunate term ordering

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#2231]
Encountered the following problem with https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/d7c52f90b15ca83a3d3f832f08989f1448fbd01e/Benchmark-Models/Bertozzi_PNAS2020:

Some expressions in dwdp that involve DiracDeltas may become NaN when evaluated for DiracDelta(0). DiracDelta(0) is currently implemented as DBL_MAX, not infinity. Therefore, `a * DiracDelta(0)` is finite for `a` in [-1, 1]. 
For the Bertozzi_PNAS2020 model, we have something like `a * DiracDelta(0) * b`, which is non-finite if `a` is outside [-1, 1], even if `a * b` would be in [-1, 1] (in this specific case, a*b == 0). Reordering the multiplicands fixes that problem.

Not sure how to handle that robustly. In this case, just moving the DiracDelta as far to the right as possible fixes the issue. However, in other situations it might be beneficial if a DiracDelta(x != 0) occurs further left.

Any thoughts?

**Comment by FFroehlich** [comment]
How do we end up with Dirac deltas in `dwdp` in the first place? Sounds like something with event parsing went awry. Having briefly looked at the model it looks like it's coming from those piecewise functions, which should be processed by https://github.com/AMICI-dev/AMICI/blob/ffcbf6652f0d9e28125647a471bd09bead78c537/python/sdist/amici/de_export.py#L2708

**Comment by dweindl** [comment]
Thanks for the pointer. I think I found the issue.
