### ISSUE TITLE
am_spline does not work correctly

### ISSUE THREAD

**Issue by AnnaFiedler** [AMICI-dev/AMICI#239]
The am_spline.m function does throw errors and is not consistent with am_spline_pos.m

**Comment by FFroehlich** [comment]
@paulstapor could you take care of this please?

**Comment by FFroehlich** [comment]
ping @paulstapor

**Comment by paulstapor** [comment]
Would "by end of April/beginning of May" work for you? I don't see any resources for me before that...

**Comment by FFroehlich** [comment]
i mean this bug, is from 2017, I guess a couple more months does not hurt ...

**Comment by FFroehlich** [comment]
ping

**Comment by dweindl** [comment]
ping :D

**Comment by paulstapor** [comment]
There is no way to encode splines in SBML. So, I don't see, there is a fix to this, except in the Matlab-interface...
We can discuss about a way to encode them in the python interface, by using whatever additional functionality, but please not in this issue...
