### ISSUE TITLE
incorrect error message in simulate_model

### ISSUE THREAD

**Issue by thomassligon** [AMICI-dev/AMICI#248]
I am running pre-equilibrium. The objective function contained
```
sol = simulate_model(Inf,...
optionsAmici.x0 = sol.x;
sol = simulate_model (data.t...
```
This produces an error
```
x0 field must be a row vector
```
which comes from simulate_model after
```
if(size(options_ami.x0,2)~=1)
```
The message should be 
```
x0 field must be a column vector
```
and the objective function must be
```
optionsAmici.x0 = transpose(sol.x);
```

**Comment by FFroehlich** [comment]
Hmm I would actually argue that `options.x0` and `sol.x` should have the same dimension (same for options.sx0 and x0, I am not sure why this is not the case. Moreover, the sizes should be checked in the cpp code and not in matlab.

**Comment by FFroehlich** [comment]
Actually `options.x0` and `sol.x0` as well as `options.sx0` and `sol.sx0` should have the same dimensions, which should already be the case. Still the error message is wrong and will be corrected.
