### ISSUE TITLE
SBML import: Incorrect processing of piecewise/Heaviside function

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#2545]
[Beer_MolBioSystems2014](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/v2024.10.15/Benchmark-Models/Beer_MolBioSystems2014) has an assignment rule containing `piecewise`. This is correctly translated to a Heaviside function during import. However, there is no corresponding root function in the generated model.

Needs further investigation.

Reminds me of #2234.

**Comment by dweindl** [comment]
Similarly for [Alkan_SciSignal2018](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/v2024.10.15/Benchmark-Models/Alkan_SciSignal2018), only that there the piecewise occurs inside a kineticLaw.

**Comment by dweindl** [comment]
So for [Beer_MolBioSystems2014](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/v2024.10.15/Benchmark-Models/Beer_MolBioSystems2014) the problem is:

https://github.com/AMICI-dev/AMICI/blob/e89a1deac59a6a65f39cb1decdf944bd13bf93f7/python/sdist/amici/de_model.py#L2275

if `dxdt` is `sympy.Heaviside`, it won't be correctly processed, because only its arguments are checked.

More or less this line of code is present since more than 4 years (https://github.com/AMICI-dev/AMICI/pull/1352). However, previously these models were imported correctly. I am not yet sure what exactly caused this problem. My guess is, that before, `dxdt` never was a plain `Heaviside`, but was always wrapped inside a `sympy.Expr`. I briefly tested sympy 1.12 and 1.11 and it still failed, so I think the relevant change was rather on the amici side than on the sympy side.

**Comment by FFroehlich** [comment]
What evidence do we have that models were imported correctly? Does the failed processing lead to an error?

**Comment by dweindl** [comment]
> What evidence do we have that models were imported correctly? Does the failed processing lead to an error?

Amici-0.11.28-generated model code from about 2 years ago that has:
```c
void root_Beer_MolBioSystems2014(realtype *root, const realtype t, const realtype *x, const realtype *p, const realtype *k, const realtype *h, const realtype *tcl){
    root[0] = t - tau;
    root[1] = -t + tau;
}
```

**Comment by dweindl** [comment]
> Similarly for [Alkan_SciSignal2018](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/v2024.10.15/Benchmark-Models/Alkan_SciSignal2018), only that there the piecewise occurs inside a kineticLaw.

False alarm for `Alkan_SciSignal2018`, there the Heaviside argument is a constant parameter. That's handled correctly.

**Comment by dweindl** [comment]
> So for [Beer_MolBioSystems2014](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/v2024.10.15/Benchmark-Models/Beer_MolBioSystems2014) the problem is:
> 
> https://github.com/AMICI-dev/AMICI/blob/e89a1deac59a6a65f39cb1decdf944bd13bf93f7/python/sdist/amici/de_model.py#L2275
> 
> if `dxdt` is `sympy.Heaviside`, it won't be correctly processed, because only its arguments are checked.
> 
> More or less this line of code is present since more than 4 years (#1352). However, previously these models were imported correctly.

This bug (or suicidal optimization), did not manifest before, because a per se meaningless multiplication with `1.0` in `_parse_piecewise_to_heaviside` ensured that `dxdt` would always be `sympy.Expr`. This changed very recently in https://github.com/AMICI-dev/AMICI/commit/b7a3e9133fd53c36daa6df6a71c580f5ff1eead2.

**This means, no AMICI-release was affected by this issue.**
