### ISSUE TITLE
Change default steady-state method to integrationOnly?

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#2571]
I would suggest to change the default steady-state methods form the current `integrateIfNewtonFails` to `integrationOnly`:

https://github.com/AMICI-dev/AMICI/blob/638c3eef18261f82192ac250f4ef3cef5a0359e4/include/amici/model.h#L2064-L2072

[Recent tests](https://doi.org/10.1371/journal.pone.0312148) showed that Newton's method may succeed finding a steady state, but the solution may not be physically feasible (e.g. negative concentrations).

For the default settings, I would prefer robustness over speed.

**Comment by FFroehlich** [comment]
Agreed.
