### ISSUE TITLE
Flaky python/tests/test_jax.py::test_conversion

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#2598]
https://github.com/AMICI-dev/AMICI/actions/runs/12019272418/job/33505489070:

```
FAILED python/tests/test_jax.py::test_conversion - AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05
field sllh does not match
Mismatched elements: 1 / 2 (50%)
Max absolute difference among violations: 1.87327994e-05
Max relative difference among violations: 2.20057975e-05
 ACTUAL: array([0.085145, 0.851285])
 DESIRED: array([0.085145, 0.851267])
 ```

**Comment by FFroehlich** [comment]
Stochasticity probably comes in during generation of synthetic data in the ExpData constructor. We can‘t even set a seed for that, right? Probably best to just set tolerances to 1e-4.

**Comment by dweindl** [comment]
> Stochasticity probably comes in during generation of synthetic data in the ExpData constructor. 

Makes sense.

> We can‘t even set a seed for that, right? 

True, we might want to change that.

> Probably best to just set tolerances to 1e-4.

Or decrease integration tolerances?
