### ISSUE TITLE
Support of observable-dependent sigmas

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#609]
Currently it is not possibly to have state-dependent sigmas. Is it only about changing respective function signatures, or will that require further adaptations?

**Comment by FFroehlich** [comment]
Would also require a couple of additional derivatives to be taken into account. On top of my head I think its only `dJydx` that needs to account for `dJydsigma*dsigmadx`, but it might be more.

**Comment by paulstapor** [comment]
I would argue, that we most likely want observable-dependent sigmas, rather than state-dependent ones.

**Comment by elbaraim** [comment]
> Yes, @elbaraim confirmed that observable dependency is what she needs in her case.

In this specific case the observables are a one-to-one mapping from the model states

**Comment by JanHasenauer** [comment]
if think that observable dependence will cover most cases. Currently, I would not bee aware of anything there we need state dependence.
If observable dependence is much easier, I would go for this.

**Comment by paulflang** [comment]
I am also running into this issue atm. What I would need is observable dependence.
