### ISSUE TITLE
Directly input ODE systems

### ISSUE THREAD

**Issue by davidsebfischer** [AMICI-dev/AMICI#654]
The idea is to replace reaction networks by ODE systems so that one can easily run parameter estimation on ODE systems that are not motivated by reaction networks. I want to run parameter estimation on ODE systems with pyPESTO so this would be the core extension necessary for that, I think the scenario appears often. I talked to @paulstapor about this and he suggested this rough guideline of what would have to be done:

This files takes SBML-files as input https://github.com/ICB-DCM/AMICI/blob/master/python/amici/sbml_import.py, there would need to be an an alternative standardised format that directly corresponds to ODE systems which would be accepted in a similar file. The output format (refer to the class ODEModel) has to be consistent with the above mentionend file and is documented here https://github.com/ICB-DCM/AMICI/blob/master/python/amici/ode_export.py.

**Comment by JanHasenauer** [comment]
The SBML format is very flexible. One way to "abuse" it is to write a single reaction for each species 0 -> X_i with the reaction rate being equal to the corresponding entry of the right-hand side of the ODE. This is a quick work-around.

I agree that it would be nice to directly input ODEs, but the implementation of this feature might need some time.

**Comment by dweindl** [comment]
Also, from the Matlab interface it is still possible to specify ODEs directly, in case this is an option.

**Comment by davidsebfischer** [comment]
@JanHasenauer and @dweindl thanks for the quick feedback! @dweindl using Matlab is not an option here unfortunately. @JanHasenauer that is a good idea, thanks! Looks as if this is fairly easy to automatise. I will give this a go!

**Comment by FFroehlich** [comment]
The best way to encode pure ODE equations is to create a SBML model with species corresponding to states with the respective rhs set as `RateRule` (see http://sbml.org/Special/specifications/sbml-level-3/version-2/core/release-1-rc2/sbml-level-3-version-2-core.pdf). This should be super straightforward to automate. Support for rate rules is not yet implemented in AMICI, but it should not be too complicated.

**Comment by dweindl** [comment]
@jvanhoefer is working on that.

**Comment by dweindl** [comment]
Update: easiest way to "directly" input ODE systems would be going via https://github.com/martamatos/yaml2sbml

- [ ] Mention in documentation
