### ISSUE TITLE
python AMICI crashes in Windows when extracting fields from rdata

### ISSUE THREAD

**Issue by LeonardSchmiester** [AMICI-dev/AMICI#670]
**What did you expect to happen?**
I compiled and wanted to simulate the Boehm model from the benchmark collection.

**What has happened instead?**
Simulating the model with `rdata = amici.runAmiciSimulation(model, solver)` seemed to work. But when running `x = rdata['x']`, I get the error `Process finished with exit code -1073741819 (0xC0000005)`.
Yannik got the output:
```
pure virtual method called
terminate called without an active exception
```

**To Reproduce**
I compiled the model with
```
sbml_importer.sbml2amici(model_name,
                         model_output_dir,
                         compiler='mingw32',
                         verbose=False,
                         observables=observables,
                         constantParameters=constant_parameter_ids,
                         sigmas=sigmas)
```
Then simulated with:
```
sys.path.insert(0, os.path.abspath(model_output_dir))
model_module = importlib.import_module(model_name)

model = model_module.getModel()

model.setTimepoints(np.linspace(0, 60, 60))

# Create solver instance
solver = model.getSolver()

# Run simulation using default model parameters and solver options
rdata = amici.runAmiciSimulation(model, solver)
x = rdata['x']
```

**AMICI version and system environment**
 - OS and version: Windows 7
 - AMICI interface: Python 
 - AMICI version: 0.10.4
 - Additional information: Installed AMICI on Windows according to #425 

**How to fix**
Yannik found this with the same output:
https://stackoverflow.com/questions/5407304/error-pure-virtual-method-called-terminate-called-without-an-active-exception

**Comment by dweindl** [comment]
Seems to be due to a clash of `libsbml ` and `amici` `SwigPyIterator`. `import libsbml` prior to `import amici` seems to solve issues on AMICI-side, without any obvious problems in `libsbml`.

Should be enough as a workaround for now. Will need some closer look if this is an issue for many users. Could try installing libsbml without wheels if somebody wants to give it a try... Marking as `wontfix` until then.

**Comment by dweindl** [comment]
If I remember correctly, this was an issue in earlier versions of libsbml and libsedml. Closing, as it didn't seem to have happened recently.
