### ISSUE TITLE
Check condition number in NewtonSolver::getSens

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#672]
NewtonSolver::getSens() willingly solved the sensitivity linear systems for a model that had a jacobian with frobenius norm ~`1e32`. Might be reasonable to warn the user that the computed sensitivities are going to be complete garbage.

**Comment by paulstapor** [comment]
I'm wondering whether or not it might be reasonable to directly compute the rank of the Jacobian in the python part already. When done, it would be clear in advance whether or not the Newton solver can actually be used or not. This would allow to avoid the Newton solver directly, if it won't be applicable anyway...

**Comment by paulstapor** [comment]
As condition numbers are not necessarily easy to compute, I was thinking that it might be reasonable to include some LA library for this. I think it's rather not the best idea to add routines for SVD or QR decomposition by hand here which would allow for condition number computation...

I was thinking of adding (and then compiling and linking) [Armadillo](http://arma.sourceforge.net/docs.html) for this task, but maybe someone of you has better ideas for this...

**Comment by FFroehlich** [comment]
What about just using `KLU_condest` https://github.com/AMICI-dev/AMICI/blob/d16078e8b6ac8b4ae31d4e7ff01738bc0291ccdd/ThirdParty/SuiteSparse/KLU/Source/klu_diagnostics.c#L164 or `KLU_rcond` https://github.com/AMICI-dev/AMICI/blob/d16078e8b6ac8b4ae31d4e7ff01738bc0291ccdd/ThirdParty/SuiteSparse/KLU/Source/klu_diagnostics.c#L489 ?

**Comment by paulstapor** [comment]
Nice!
Didn't know those existed... Yes, sure, that's preferred then!
