### ISSUE TITLE
Python package installation from python/sdist/ broken

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#716]
Only the development installation with `pip -e` or via sdist works. This is due to  the symlink to README.md. Needs to be cleaned up somehow.

**Comment by dweindl** [comment]
Without this being addressed, Python package installations from the github repository won't work for Windows users. (Does not affect installation of source distributions created elsewhere.)

**Comment by dweindl** [comment]
Fixing this also for Windows users is a bit tricky. Problem is that Python setuptools expects the same directory structure in the repository as we want to have in the installation directory. This is no problem for Python-only projects, but causes trouble here if we want to separate the different interfaces. Same problem with the current implementation of enscons.

Options:
1. keeping things as they are (symlinks to create required python package structure)
  * ++ separation of interfaces
  * ++ supports editable installation
  * -- won't work for windows
2. creating the required directory structure from cmake in a temporary directory
  * ++ separation of interfaces
  * ++ works for windows
  * -- requires cmake (minor)
  * -- breaks editable pip installation
3. rearrange directory structure for setuptools
  * ++ works on windows
  * ++ supports editable installation
  * -- is a big mess, no separation of interfaces
4. modifying setuptools or enscons behaviour to allow specifying destination of files in package
  * -- lot's of work
  * -- breaks editable pip installation

Any ideas who to handle that in a nicer way?

**Comment by paulstapor** [comment]
What do you precisely mean by "separation of interfaces"?

**Comment by dweindl** [comment]
> What do you precisely mean by "separation of interfaces"?

Keeping the C++/Matlab/Python/.. files in separate folders instead of pressing everything in a shape working for Python setuptools.

**Comment by dweindl** [comment]
Update: The problem is not only the readme symlink which would be easy to fix, but it applies to many other files, especially everything below `ThirdParty/`. 

This is intended behavior of `pip`. So "wontfix". The way to go is via `sdist`.

**Comment by dweindl** [comment]
Actually `cd python/sdist && python setup.py install` works, only `cd python/sdist && pip install .` fails.

**Comment by dweindl** [comment]
> only `cd python/sdist && pip install .` fails.

Seems to work meanwhile. (Tested on Ubuntu 24.04, python 3.12, pip 24.2, setuptools-75.1.0).
