### ISSUE TITLE
solver.setMaxSteps() is not working correctly

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#726]
I managed to simulate a model past (as indicated by `rdata['numsteps'])` the specified number of maximal steps specified by `solver.setMaxSteps()` . Seems to be dependent on specifying simulation timepoints prior to to the timepoint where the maximum number of steps is reached. Current hypothesis is that only number of steps between timepoints in penalized and not total.

**Comment by dweindl** [comment]
> Current hypothesis is that only number of steps between timepoints in penalized and not total.

Yes. From the sundials doc:
> The function CVodeSetMaxNumStepsspecifies the maximum number of steps to be taken by the solver in its attempt *to reach the next output time*.
