### ISSUE TITLE
Allow specifying maximum integration time in addition to maximum integration steps

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#748]
Currently it is possible to set a maximum number of integration steps to perform before integration is aborted. It would be to complement that by a maximum time. 
This would be helpful during optimization, when initially simulations with random parameters may take very long and they could be aborted after a specified time and retried with looser integration tolerances.

**Comment by dweindl** [comment]
I might start working on this one. 

@FFroehlich : What do you think would be the best place to check whether we are exceeding the given time span? Calls to J? Calls to CVode?

**Comment by FFroehlich** [comment]
> I might start working on this one.
> 
> @FFroehlich : What do you think would be the best place to check whether we are exceeding the given time span? Calls to J? Calls to CVode?

Would recommend 
https://github.com/AMICI-dev/AMICI/blob/c0377065207b68c881143d203de1f56fd52878b9/src/model_ode.cpp#L94
CVodes uses an adaptive method when J needs to be updated, so it is usually evaluated less frequently than fxdot

**Comment by dweindl** [comment]
It would be most convenient to implement as an option in `amici::Model`, but that feels wrong. 

Could add the option to `amici::Solver` and instead check in https://github.com/AMICI-dev/AMICI/blob/c0377065207b68c881143d203de1f56fd52878b9/src/solver_cvodes.cpp#L42 and https://github.com/AMICI-dev/AMICI/blob/c0377065207b68c881143d203de1f56fd52878b9/src/solver_cvodes.cpp#L76. The `Solver` is currently not accessible there, but could add it to cvodes `user_data`. That will not catch the direct `Model_ODE::fxdot` calls, but shouldn't matter much for most application.

Running `runAmiciSimulation` in a separate thread and canceling that thread after the given time limit would be another option, but rather too invasive.

**Comment by FFroehlich** [comment]
> It would be most convenient to implement as an option in `amici::Model`, but that feels wrong.
> 
> Could add the option to `amici::Solver` and instead check in
> 
> https://github.com/AMICI-dev/AMICI/blob/c0377065207b68c881143d203de1f56fd52878b9/src/solver_cvodes.cpp#L42
> 
> and
> https://github.com/AMICI-dev/AMICI/blob/c0377065207b68c881143d203de1f56fd52878b9/src/solver_cvodes.cpp#L76
> 
> . The `Solver` is currently not accessible there, but could add it to cvodes `user_data`. That will not catch the direct `Model_ODE::fxdot` calls, but shouldn't matter much for most application.

Yep, sounds good!
