### ISSUE TITLE
PetabObjective

### ISSUE THREAD

**Issue by yannikschaelte** [AMICI-dev/AMICI#962]
Create a class encapsulating the petab simulation functionality, in particular later allowing to cache e.g. mappings to increase efficiency.

**Comment by dweindl** [comment]
Will look into that. Was thinking about some `AmiciPetabProblem` class that takes the model and the PEtab problem and can be used to create ExpData for the PEtab-defined conditions. Probably with some option to cache or always recreate the ExpDatas (the former would generally be faster, the latter would be more memory-efficient).

This should make it easier to simulate the model for specific conditions, in particular in interactive use.

**Comment by dweindl** [comment]
Closed by #2255
