### ISSUE TITLE
Gradient tests for benchmark collection

### ISSUE THREAD

**Issue by yannikschaelte** [AMICI-dev/AMICI#967]
A lot can go wrong with wrong parameter scales, thus there should be gradient tests for (some of) the benchmark models. Suggest FDs, maybe at (deterministically sampled) random parameters (as the gradients at the optimum tend to be rather sensitive).

**Comment by dweindl** [comment]
See also #944

**Comment by dweindl** [comment]
Implemented for PEtab test cases in `tests/petab_test_suite`. Might still be good to test for some more models...

**Comment by FFroehlich** [comment]
https://github.com/wesselb/fdm might be relevant here

**Comment by dweindl** [comment]
Done in https://github.com/AMICI-dev/AMICI/pull/1548
