### ISSUE TITLE
PEtab: set t0

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#999]
For test case see: https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/issues/45

**Comment by dweindl** [comment]
Not sure how to handle this, as starting time is not defined in PEtab.

**Comment by FFroehlich** [comment]
No an amici problem? `Model::setT0(...)` can be used to set T0. Could also add a field for that to ExpData.

**Comment by dweindl** [comment]
Not an AMICI problem, so should probably close. Adding it to ExpData would be good though.
